# TCL File Generated by Component Editor 12.0
# Fri Feb 22 11:16:54 GMT 2013
# DO NOT MODIFY


# 
# fp_alu "fp_alu" v1.0
# null 2013.02.22.11:16:54
# 
# 

# 
# request TCL package from ACDS 12.0
# 
package require -exact qsys 12.0


# 
# module fp_alu
# 
set_module_property NAME fp_alu
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME fp_alu
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL fp_alu_improved
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file fp_alu_improved.v VERILOG PATH ip/fp_alu_improved.v


# 
# parameters
# 
add_parameter NaN STD_LOGIC_VECTOR 2147483647
set_parameter_property NaN DEFAULT_VALUE 2147483647
set_parameter_property NaN DISPLAY_NAME NaN
set_parameter_property NaN TYPE STD_LOGIC_VECTOR
set_parameter_property NaN UNITS None
set_parameter_property NaN ALLOWED_RANGES 0:17179869183


# 
# display items
# 


# 
# connection point nios_custom_instruction_slave
# 
add_interface nios_custom_instruction_slave nios_custom_instruction end
set_interface_property nios_custom_instruction_slave clockCycle 0
set_interface_property nios_custom_instruction_slave operands 2
set_interface_property nios_custom_instruction_slave ENABLED true

add_interface_port nios_custom_instruction_slave n n Input 2
add_interface_port nios_custom_instruction_slave done done Output 1
add_interface_port nios_custom_instruction_slave result result Output 32
add_interface_port nios_custom_instruction_slave clk clk Input 1
add_interface_port nios_custom_instruction_slave clk_en clk_en Input 1
add_interface_port nios_custom_instruction_slave start start Input 1
add_interface_port nios_custom_instruction_slave reset reset Input 1
add_interface_port nios_custom_instruction_slave dataa dataa Input 32
add_interface_port nios_custom_instruction_slave datab datab Input 32

