# TCL File Generated by Component Editor 12.0
# Tue Mar 19 20:04:40 GMT 2013
# DO NOT MODIFY


# 
# fp_det_nios "fp_det_nios" v1.0
# null 2013.03.19.20:04:40
# 
# 

# 
# request TCL package from ACDS 12.0
# 
package require -exact qsys 12.0


# 
# module fp_det_nios
# 
set_module_property NAME fp_det_nios
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME fp_det_nios
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL fp_det_nios
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file fp_det_nios.v VERILOG PATH ip/fp_det_nios.v


# 
# parameters
# 
add_parameter DEFAULT_DIMENSION INTEGER 10
set_parameter_property DEFAULT_DIMENSION DEFAULT_VALUE 10
set_parameter_property DEFAULT_DIMENSION DISPLAY_NAME DEFAULT_DIMENSION
set_parameter_property DEFAULT_DIMENSION TYPE INTEGER
set_parameter_property DEFAULT_DIMENSION UNITS None
set_parameter_property DEFAULT_DIMENSION ALLOWED_RANGES -2147483648:2147483647
add_parameter ADDER_LATENCY INTEGER 7
set_parameter_property ADDER_LATENCY DEFAULT_VALUE 7
set_parameter_property ADDER_LATENCY DISPLAY_NAME ADDER_LATENCY
set_parameter_property ADDER_LATENCY TYPE INTEGER
set_parameter_property ADDER_LATENCY UNITS None
add_parameter MULTPLIER_LATENCY INTEGER 5
set_parameter_property MULTPLIER_LATENCY DEFAULT_VALUE 5
set_parameter_property MULTPLIER_LATENCY DISPLAY_NAME MULTPLIER_LATENCY
set_parameter_property MULTPLIER_LATENCY TYPE INTEGER
set_parameter_property MULTPLIER_LATENCY UNITS None
add_parameter DIVIDER_LATENCY INTEGER 6
set_parameter_property DIVIDER_LATENCY DEFAULT_VALUE 6
set_parameter_property DIVIDER_LATENCY DISPLAY_NAME DIVIDER_LATENCY
set_parameter_property DIVIDER_LATENCY TYPE INTEGER
set_parameter_property DIVIDER_LATENCY UNITS None
add_parameter MAX_DIMENSION INTEGER 32
set_parameter_property MAX_DIMENSION DEFAULT_VALUE 32
set_parameter_property MAX_DIMENSION DISPLAY_NAME MAX_DIMENSION
set_parameter_property MAX_DIMENSION TYPE INTEGER
set_parameter_property MAX_DIMENSION UNITS None
add_parameter NaN STD_LOGIC_VECTOR 2143289344
set_parameter_property NaN DEFAULT_VALUE 2143289344
set_parameter_property NaN DISPLAY_NAME NaN
set_parameter_property NaN TYPE STD_LOGIC_VECTOR
set_parameter_property NaN UNITS None
set_parameter_property NaN ALLOWED_RANGES 0:17179869183
add_parameter FLOAT_ONE STD_LOGIC_VECTOR 1065353216
set_parameter_property FLOAT_ONE DEFAULT_VALUE 1065353216
set_parameter_property FLOAT_ONE DISPLAY_NAME FLOAT_ONE
set_parameter_property FLOAT_ONE TYPE STD_LOGIC_VECTOR
set_parameter_property FLOAT_ONE UNITS None
set_parameter_property FLOAT_ONE ALLOWED_RANGES 0:17179869183


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true

add_interface_port clock_sink avalon_clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true

add_interface_port reset_sink avalon_reset reset Input 1


# 
# connection point nios_custom_instruction_slave
# 
add_interface nios_custom_instruction_slave nios_custom_instruction end
set_interface_property nios_custom_instruction_slave clockCycle 0
set_interface_property nios_custom_instruction_slave operands 2
set_interface_property nios_custom_instruction_slave ENABLED true

add_interface_port nios_custom_instruction_slave clk clk Input 1
add_interface_port nios_custom_instruction_slave dataa dataa Input 32
add_interface_port nios_custom_instruction_slave datab datab Input 32
add_interface_port nios_custom_instruction_slave result result Output 32
add_interface_port nios_custom_instruction_slave clk_en clk_en Input 1
add_interface_port nios_custom_instruction_slave start start Input 1
add_interface_port nios_custom_instruction_slave done done Output 1
add_interface_port nios_custom_instruction_slave reset reset Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock_sink
set_interface_property avalon_master associatedReset reset_sink
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master ENABLED true

add_interface_port avalon_master address address Output 24
add_interface_port avalon_master read read Output 1
add_interface_port avalon_master readdata readdata Input 32
add_interface_port avalon_master readdatavalid readdatavalid Input 1
add_interface_port avalon_master waitrequest waitrequest Input 1
add_interface_port avalon_master write write Output 1
add_interface_port avalon_master writedata writedata Output 32


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressAlignment DYNAMIC
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock_sink
set_interface_property avalon_slave associatedReset reset_sink
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave isMemoryDevice false
set_interface_property avalon_slave isNonVolatileStorage false
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave printableDevice false
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true

add_interface_port avalon_slave result_read read Input 1
add_interface_port avalon_slave result_readdata readdata Output 32


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint avalon_slave
set_interface_property interrupt_sender associatedClock clock_sink
set_interface_property interrupt_sender associatedReset reset_sink
set_interface_property interrupt_sender ENABLED true

add_interface_port interrupt_sender irq irq Output 1

