# TCL File Generated by Component Editor 12.0
# Sat Mar 16 22:13:45 GMT 2013
# DO NOT MODIFY


# 
# notch "notch" v1.0
# null 2013.03.16.22:13:45
# 
# 

# 
# request TCL package from ACDS 12.0
# 
package require -exact qsys 12.0


# 
# module notch
# 
set_module_property NAME notch
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME notch
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL notch
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file notch.v VERILOG PATH ip/notch.v


# 
# parameters
# 
add_parameter N INTEGER 2
set_parameter_property N DEFAULT_VALUE 2
set_parameter_property N DISPLAY_NAME N
set_parameter_property N TYPE INTEGER
set_parameter_property N UNITS None
set_parameter_property N ALLOWED_RANGES -2147483648:2147483647
add_parameter NO_SAMPLES INTEGER 963144
set_parameter_property NO_SAMPLES DEFAULT_VALUE 963144
set_parameter_property NO_SAMPLES DISPLAY_NAME NO_SAMPLES
set_parameter_property NO_SAMPLES TYPE INTEGER
set_parameter_property NO_SAMPLES UNITS None
set_parameter_property NO_SAMPLES ALLOWED_RANGES -2147483648:2147483647
add_parameter SAMPLE_SCALING INTEGER 2147483647
set_parameter_property SAMPLE_SCALING DEFAULT_VALUE 2147483647
set_parameter_property SAMPLE_SCALING DISPLAY_NAME SAMPLE_SCALING
set_parameter_property SAMPLE_SCALING TYPE INTEGER
set_parameter_property SAMPLE_SCALING UNITS None
set_parameter_property SAMPLE_SCALING ALLOWED_RANGES -2147483648:2147483647
add_parameter COEFF_SCALING INTEGER 16383
set_parameter_property COEFF_SCALING DEFAULT_VALUE 16383
set_parameter_property COEFF_SCALING DISPLAY_NAME COEFF_SCALING
set_parameter_property COEFF_SCALING TYPE INTEGER
set_parameter_property COEFF_SCALING UNITS None
set_parameter_property COEFF_SCALING ALLOWED_RANGES -2147483648:2147483647
add_parameter DIVIDER_LATENCY INTEGER 16 ""
set_parameter_property DIVIDER_LATENCY DEFAULT_VALUE 16
set_parameter_property DIVIDER_LATENCY DISPLAY_NAME DIVIDER_LATENCY
set_parameter_property DIVIDER_LATENCY TYPE INTEGER
set_parameter_property DIVIDER_LATENCY UNITS None
set_parameter_property DIVIDER_LATENCY ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DIVIDER_LATENCY DESCRIPTION ""
add_parameter SDRAM_WORD_SKIP INTEGER 4
set_parameter_property SDRAM_WORD_SKIP DEFAULT_VALUE 4
set_parameter_property SDRAM_WORD_SKIP DISPLAY_NAME SDRAM_WORD_SKIP
set_parameter_property SDRAM_WORD_SKIP TYPE INTEGER
set_parameter_property SDRAM_WORD_SKIP UNITS None
set_parameter_property SDRAM_WORD_SKIP ALLOWED_RANGES -2147483648:2147483647


# 
# display items
# 


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressAlignment DYNAMIC
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock_sink
set_interface_property avalon_slave associatedReset reset_sink
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave isMemoryDevice false
set_interface_property avalon_slave isNonVolatileStorage false
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave printableDevice false
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitStates 1
set_interface_property avalon_slave writeWaitTime 1
set_interface_property avalon_slave ENABLED true

add_interface_port avalon_slave slave_read read Input 1
add_interface_port avalon_slave slave_readdata readdata Output 32
add_interface_port avalon_slave slave_write write Input 1
add_interface_port avalon_slave slave_writedata writedata Input 32
add_interface_port avalon_slave slave_address address Input 4


# 
# connection point sd_master
# 
add_interface sd_master avalon start
set_interface_property sd_master addressUnits SYMBOLS
set_interface_property sd_master associatedClock clock_sink
set_interface_property sd_master associatedReset reset_sink
set_interface_property sd_master burstOnBurstBoundariesOnly false
set_interface_property sd_master doStreamReads false
set_interface_property sd_master doStreamWrites false
set_interface_property sd_master linewrapBursts false
set_interface_property sd_master readLatency 0
set_interface_property sd_master ENABLED true

add_interface_port sd_master sdaddress address Output 24
add_interface_port sd_master sdread read Output 1
add_interface_port sd_master sdreaddata readdata Input 32
add_interface_port sd_master sdreaddatavalid readdatavalid Input 1
add_interface_port sd_master sdwaitrequest waitrequest Input 1
add_interface_port sd_master sdwrite write Output 1
add_interface_port sd_master sdwritedata writedata Output 32


# 
# connection point nios_custom_instruction_slave
# 
add_interface nios_custom_instruction_slave nios_custom_instruction end
set_interface_property nios_custom_instruction_slave clockCycle 0
set_interface_property nios_custom_instruction_slave operands 2
set_interface_property nios_custom_instruction_slave ENABLED true

add_interface_port nios_custom_instruction_slave clk clk Input 1
add_interface_port nios_custom_instruction_slave dataa dataa Input 32
add_interface_port nios_custom_instruction_slave datab datab Input 32
add_interface_port nios_custom_instruction_slave result result Output 32
add_interface_port nios_custom_instruction_slave clk_en clk_en Input 1
add_interface_port nios_custom_instruction_slave start start Input 1
add_interface_port nios_custom_instruction_slave done done Output 1
add_interface_port nios_custom_instruction_slave reset reset Input 1


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint avalon_slave
set_interface_property interrupt_sender associatedClock clock_sink
set_interface_property interrupt_sender associatedReset reset_sink
set_interface_property interrupt_sender ENABLED true

add_interface_port interrupt_sender irq irq Output 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true

add_interface_port clock_sink avalon_clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true

add_interface_port reset_sink avalon_reset reset Input 1

