# TCL File Generated by Component Editor 12.0
# Thu Mar 14 10:31:55 GMT 2013
# DO NOT MODIFY


# 
# notch "notch" v1.0
# null 2013.03.14.10:31:55
# 
# 

# 
# request TCL package from ACDS 12.0
# 
package require -exact qsys 12.0


# 
# module notch
# 
set_module_property NAME notch
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME notch
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL notch
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file notch.v VERILOG PATH ip/notch.v


# 
# parameters
# 
add_parameter N INTEGER 2
set_parameter_property N DEFAULT_VALUE 2
set_parameter_property N DISPLAY_NAME N
set_parameter_property N TYPE INTEGER
set_parameter_property N UNITS None
add_parameter NO_SAMPLES INTEGER 963144
set_parameter_property NO_SAMPLES DEFAULT_VALUE 963144
set_parameter_property NO_SAMPLES DISPLAY_NAME NO_SAMPLES
set_parameter_property NO_SAMPLES TYPE INTEGER
set_parameter_property NO_SAMPLES UNITS None
add_parameter SAMPLE_SCALING INTEGER 2147483647
set_parameter_property SAMPLE_SCALING DEFAULT_VALUE 2147483647
set_parameter_property SAMPLE_SCALING DISPLAY_NAME SAMPLE_SCALING
set_parameter_property SAMPLE_SCALING TYPE INTEGER
set_parameter_property SAMPLE_SCALING UNITS None
add_parameter COEFF_SCALING INTEGER 16383
set_parameter_property COEFF_SCALING DEFAULT_VALUE 16383
set_parameter_property COEFF_SCALING DISPLAY_NAME COEFF_SCALING
set_parameter_property COEFF_SCALING TYPE INTEGER
set_parameter_property COEFF_SCALING UNITS None
add_parameter FLASH_BASE_ADDRESS INTEGER 0
set_parameter_property FLASH_BASE_ADDRESS DEFAULT_VALUE 0
set_parameter_property FLASH_BASE_ADDRESS DISPLAY_NAME FLASH_BASE_ADDRESS
set_parameter_property FLASH_BASE_ADDRESS TYPE INTEGER
set_parameter_property FLASH_BASE_ADDRESS UNITS None
add_parameter A1 STD_LOGIC_VECTOR 34501
set_parameter_property A1 DEFAULT_VALUE 34501
set_parameter_property A1 DISPLAY_NAME A1
set_parameter_property A1 TYPE STD_LOGIC_VECTOR
set_parameter_property A1 UNITS None
set_parameter_property A1 ALLOWED_RANGES 0:262143
add_parameter A2 STD_LOGIC_VECTOR 14969
set_parameter_property A2 DEFAULT_VALUE 14969
set_parameter_property A2 DISPLAY_NAME A2
set_parameter_property A2 TYPE STD_LOGIC_VECTOR
set_parameter_property A2 UNITS None
set_parameter_property A2 ALLOWED_RANGES 0:262143
add_parameter B0 STD_LOGIC_VECTOR 8275
set_parameter_property B0 DEFAULT_VALUE 8275
set_parameter_property B0 DISPLAY_NAME B0
set_parameter_property B0 TYPE STD_LOGIC_VECTOR
set_parameter_property B0 UNITS None
set_parameter_property B0 ALLOWED_RANGES 0:262143
add_parameter B1 STD_LOGIC_VECTOR 49153
set_parameter_property B1 DEFAULT_VALUE 49153
set_parameter_property B1 DISPLAY_NAME B1
set_parameter_property B1 TYPE STD_LOGIC_VECTOR
set_parameter_property B1 UNITS None
set_parameter_property B1 ALLOWED_RANGES 0:262143
add_parameter B2 STD_LOGIC_VECTOR 8275
set_parameter_property B2 DEFAULT_VALUE 8275
set_parameter_property B2 DISPLAY_NAME B2
set_parameter_property B2 TYPE STD_LOGIC_VECTOR
set_parameter_property B2 UNITS None
set_parameter_property B2 ALLOWED_RANGES 0:262143


# 
# display items
# 


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressAlignment DYNAMIC
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock_sink
set_interface_property avalon_slave associatedReset reset_sink
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave isMemoryDevice false
set_interface_property avalon_slave isNonVolatileStorage false
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave printableDevice false
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitStates 1
set_interface_property avalon_slave writeWaitTime 1
set_interface_property avalon_slave ENABLED true

add_interface_port avalon_slave slave_read read Input 1
add_interface_port avalon_slave slave_readdata readdata Output 32
add_interface_port avalon_slave slave_write write Input 1
add_interface_port avalon_slave slave_writedata writedata Input 32
add_interface_port avalon_slave address address Input 3


# 
# connection point sd_master
# 
add_interface sd_master avalon start
set_interface_property sd_master addressUnits SYMBOLS
set_interface_property sd_master associatedClock clock_sink
set_interface_property sd_master associatedReset reset_sink
set_interface_property sd_master burstOnBurstBoundariesOnly false
set_interface_property sd_master doStreamReads false
set_interface_property sd_master doStreamWrites false
set_interface_property sd_master linewrapBursts false
set_interface_property sd_master readLatency 0
set_interface_property sd_master ENABLED true

add_interface_port sd_master sdaddress address Output 24
add_interface_port sd_master sdread read Output 1
add_interface_port sd_master sdreaddata readdata Input 32
add_interface_port sd_master sdreaddatavalid readdatavalid Input 1
add_interface_port sd_master sdwaitrequest waitrequest Input 1
add_interface_port sd_master sdwrite write Output 1
add_interface_port sd_master sdwritedata writedata Output 32


# 
# connection point flash_master
# 
add_interface flash_master avalon start
set_interface_property flash_master addressUnits SYMBOLS
set_interface_property flash_master associatedClock clock_sink
set_interface_property flash_master associatedReset reset_sink
set_interface_property flash_master burstOnBurstBoundariesOnly false
set_interface_property flash_master doStreamReads false
set_interface_property flash_master doStreamWrites false
set_interface_property flash_master linewrapBursts false
set_interface_property flash_master readLatency 0
set_interface_property flash_master ENABLED true

add_interface_port flash_master fladdress address Output 22
add_interface_port flash_master flread read Output 1
add_interface_port flash_master flreaddata readdata Input 32
add_interface_port flash_master flreaddatavalid readdatavalid Input 1
add_interface_port flash_master flwaitrequest waitrequest Input 1
add_interface_port flash_master flwrite write Output 1
add_interface_port flash_master flwritedata writedata Output 32


# 
# connection point nios_custom_instruction_slave
# 
add_interface nios_custom_instruction_slave nios_custom_instruction end
set_interface_property nios_custom_instruction_slave clockCycle 0
set_interface_property nios_custom_instruction_slave operands 2
set_interface_property nios_custom_instruction_slave ENABLED true

add_interface_port nios_custom_instruction_slave clk clk Input 1
add_interface_port nios_custom_instruction_slave dataa dataa Input 32
add_interface_port nios_custom_instruction_slave datab datab Input 32
add_interface_port nios_custom_instruction_slave result result Output 32
add_interface_port nios_custom_instruction_slave clk_en clk_en Input 1
add_interface_port nios_custom_instruction_slave start start Input 1
add_interface_port nios_custom_instruction_slave done done Output 1
add_interface_port nios_custom_instruction_slave reset reset Input 1


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint avalon_slave
set_interface_property interrupt_sender associatedClock clock_sink
set_interface_property interrupt_sender associatedReset reset_sink
set_interface_property interrupt_sender ENABLED true

add_interface_port interrupt_sender irq irq Output 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true

add_interface_port clock_sink avalon_clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true

add_interface_port reset_sink avalon_reset reset Input 1

