// megafunction wizard: %ALTFP_DIV%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: altfp_div 

// ============================================================
// File Name: fp_div.v
// Megafunction Name(s):
// 			altfp_div
//
// Simulation Library Files(s):
// 			
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 12.0 Build 178 05/31/2012 SJ Full Version
// ************************************************************


//Copyright (C) 1991-2012 Altera Corporation
//Your use of Altera Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Altera Program License 
//Subscription Agreement, Altera MegaCore Function License 
//Agreement, or other applicable license agreement, including, 
//without limitation, that your use is for the sole purpose of 
//programming logic devices manufactured by Altera and sold by 
//Altera or its authorized distributors.  Please refer to the 
//applicable agreement for further details.


//altfp_div DENORMAL_SUPPORT="NO" DEVICE_FAMILY="Cyclone III" OPTIMIZE="SPEED" PIPELINE=6 REDUCED_FUNCTIONALITY="NO" WIDTH_EXP=8 WIDTH_MAN=23 aclr clk_en clock dataa datab nan result zero
//VERSION_BEGIN 12.0 cbx_altbarrel_shift 2012:05:31:20:08:02:SJ cbx_altfp_div 2012:05:31:20:08:02:SJ cbx_altsyncram 2012:05:31:20:08:02:SJ cbx_cycloneii 2012:05:31:20:08:02:SJ cbx_lpm_abs 2012:05:31:20:08:02:SJ cbx_lpm_add_sub 2012:05:31:20:08:02:SJ cbx_lpm_compare 2012:05:31:20:08:02:SJ cbx_lpm_decode 2012:05:31:20:08:02:SJ cbx_lpm_divide 2012:05:31:20:08:02:SJ cbx_lpm_mult 2012:05:31:20:08:02:SJ cbx_lpm_mux 2012:05:31:20:08:02:SJ cbx_mgl 2012:05:31:20:10:16:SJ cbx_padd 2012:05:31:20:08:02:SJ cbx_stratix 2012:05:31:20:08:02:SJ cbx_stratixii 2012:05:31:20:08:02:SJ cbx_stratixiii 2012:05:31:20:08:02:SJ cbx_stratixv 2012:05:31:20:08:02:SJ cbx_util_mgl 2012:05:31:20:08:02:SJ  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463



//altfp_div_pst DEVICE_FAMILY="Cyclone III" FILE_NAME="fp_div_syn.v:a" PIPELINE=6 WIDTH_EXP=8 WIDTH_MAN=23 aclr clk_en clock dataa datab nan result zero
//VERSION_BEGIN 12.0 cbx_altbarrel_shift 2012:05:31:20:08:02:SJ cbx_altfp_div 2012:05:31:20:08:02:SJ cbx_altsyncram 2012:05:31:20:08:02:SJ cbx_cycloneii 2012:05:31:20:08:02:SJ cbx_lpm_abs 2012:05:31:20:08:02:SJ cbx_lpm_add_sub 2012:05:31:20:08:02:SJ cbx_lpm_compare 2012:05:31:20:08:02:SJ cbx_lpm_decode 2012:05:31:20:08:02:SJ cbx_lpm_divide 2012:05:31:20:08:02:SJ cbx_lpm_mult 2012:05:31:20:08:02:SJ cbx_lpm_mux 2012:05:31:20:08:02:SJ cbx_mgl 2012:05:31:20:10:16:SJ cbx_padd 2012:05:31:20:08:02:SJ cbx_stratix 2012:05:31:20:08:02:SJ cbx_stratixii 2012:05:31:20:08:02:SJ cbx_stratixiii 2012:05:31:20:08:02:SJ cbx_stratixv 2012:05:31:20:08:02:SJ cbx_util_mgl 2012:05:31:20:08:02:SJ  VERSION_END


//altsyncram DEVICE_FAMILY="Cyclone III" INIT_FILE="fp_div_syn.hex" OPERATION_MODE="ROM" WIDTH_A=9 WIDTHAD_A=9 address_a clock0 clocken0 q_a
//VERSION_BEGIN 12.0 cbx_altsyncram 2012:05:31:20:08:02:SJ cbx_cycloneii 2012:05:31:20:08:02:SJ cbx_lpm_add_sub 2012:05:31:20:08:02:SJ cbx_lpm_compare 2012:05:31:20:08:02:SJ cbx_lpm_decode 2012:05:31:20:08:02:SJ cbx_lpm_mux 2012:05:31:20:08:02:SJ cbx_mgl 2012:05:31:20:10:16:SJ cbx_stratix 2012:05:31:20:08:02:SJ cbx_stratixii 2012:05:31:20:08:02:SJ cbx_stratixiii 2012:05:31:20:08:02:SJ cbx_stratixv 2012:05:31:20:08:02:SJ cbx_util_mgl 2012:05:31:20:08:02:SJ  VERSION_END

//synthesis_resources = M9K 1 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"OPTIMIZE_POWER_DURING_SYNTHESIS=NORMAL_COMPILATION"} *)
module  fp_div_altsyncram
	( 
	address_a,
	clock0,
	clocken0,
	q_a) /* synthesis synthesis_clearbox=1 */;
	input   [8:0]  address_a;
	input   clock0;
	input   clocken0;
	output   [8:0]  q_a;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri1   clock0;
	tri1   clocken0;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [0:0]   wire_ram_block4a_0portadataout;
	wire  [0:0]   wire_ram_block4a_1portadataout;
	wire  [0:0]   wire_ram_block4a_2portadataout;
	wire  [0:0]   wire_ram_block4a_3portadataout;
	wire  [0:0]   wire_ram_block4a_4portadataout;
	wire  [0:0]   wire_ram_block4a_5portadataout;
	wire  [0:0]   wire_ram_block4a_6portadataout;
	wire  [0:0]   wire_ram_block4a_7portadataout;
	wire  [0:0]   wire_ram_block4a_8portadataout;
	wire  [8:0]  address_a_wire;

	cycloneiii_ram_block   ram_block4a_0
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[8:0]}),
	.portadataout(wire_ram_block4a_0portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block4a_0.clk0_core_clock_enable = "ena0",
		ram_block4a_0.clk0_input_clock_enable = "ena0",
		ram_block4a_0.connectivity_checking = "OFF",
		ram_block4a_0.init_file = "fp_div_syn.hex",
		ram_block4a_0.init_file_layout = "port_a",
		ram_block4a_0.logical_ram_name = "ALTSYNCRAM",
		ram_block4a_0.mem_init0 = 512'h333333336664CD99326CD93649B249B6DB6DB6D24B692D2D2D694A52B5AB56A954AAB5555555555552AA55AB52B4A5A5B49249B264CCCCCE639C70E1F07F0000,
		ram_block4a_0.operation_mode = "rom",
		ram_block4a_0.port_a_address_width = 9,
		ram_block4a_0.port_a_data_out_clear = "none",
		ram_block4a_0.port_a_data_out_clock = "none",
		ram_block4a_0.port_a_data_width = 1,
		ram_block4a_0.port_a_first_address = 0,
		ram_block4a_0.port_a_first_bit_number = 0,
		ram_block4a_0.port_a_last_address = 511,
		ram_block4a_0.port_a_logical_ram_depth = 512,
		ram_block4a_0.port_a_logical_ram_width = 9,
		ram_block4a_0.ram_block_type = "AUTO",
		ram_block4a_0.lpm_type = "cycloneiii_ram_block";
	cycloneiii_ram_block   ram_block4a_1
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[8:0]}),
	.portadataout(wire_ram_block4a_1portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block4a_1.clk0_core_clock_enable = "ena0",
		ram_block4a_1.clk0_input_clock_enable = "ena0",
		ram_block4a_1.connectivity_checking = "OFF",
		ram_block4a_1.init_file = "fp_div_syn.hex",
		ram_block4a_1.init_file_layout = "port_a",
		ram_block4a_1.logical_ram_name = "ALTSYNCRAM",
		ram_block4a_1.mem_init0 = 512'h0F0F0F0F1E1C3C78F1E3C70E3871C78E38E38E31C718E31CE318C6318C673198CC667333333333333666CC99366D936C92492496D25A5A5AD6B52A54AAD55555,
		ram_block4a_1.operation_mode = "rom",
		ram_block4a_1.port_a_address_width = 9,
		ram_block4a_1.port_a_data_out_clear = "none",
		ram_block4a_1.port_a_data_out_clock = "none",
		ram_block4a_1.port_a_data_width = 1,
		ram_block4a_1.port_a_first_address = 0,
		ram_block4a_1.port_a_first_bit_number = 1,
		ram_block4a_1.port_a_last_address = 511,
		ram_block4a_1.port_a_logical_ram_depth = 512,
		ram_block4a_1.port_a_logical_ram_width = 9,
		ram_block4a_1.ram_block_type = "AUTO",
		ram_block4a_1.lpm_type = "cycloneiii_ram_block";
	cycloneiii_ram_block   ram_block4a_2
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[8:0]}),
	.portadataout(wire_ram_block4a_2portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block4a_2.clk0_core_clock_enable = "ena0",
		ram_block4a_2.clk0_input_clock_enable = "ena0",
		ram_block4a_2.connectivity_checking = "OFF",
		ram_block4a_2.init_file = "fp_div_syn.hex",
		ram_block4a_2.init_file_layout = "port_a",
		ram_block4a_2.logical_ram_name = "ALTSYNCRAM",
		ram_block4a_2.mem_init0 = 512'h00FF00FF01FC03F80FE03F01F80FC07E07E07E0FC0F81F03E0F83E0F83E0F0783C1E0F0F0F0F0F0F0E1E3C78F1E38F1C71C71C71CE39C639CE7319CC66333333,
		ram_block4a_2.operation_mode = "rom",
		ram_block4a_2.port_a_address_width = 9,
		ram_block4a_2.port_a_data_out_clear = "none",
		ram_block4a_2.port_a_data_out_clock = "none",
		ram_block4a_2.port_a_data_width = 1,
		ram_block4a_2.port_a_first_address = 0,
		ram_block4a_2.port_a_first_bit_number = 2,
		ram_block4a_2.port_a_last_address = 511,
		ram_block4a_2.port_a_logical_ram_depth = 512,
		ram_block4a_2.port_a_logical_ram_width = 9,
		ram_block4a_2.ram_block_type = "AUTO",
		ram_block4a_2.lpm_type = "cycloneiii_ram_block";
	cycloneiii_ram_block   ram_block4a_3
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[8:0]}),
	.portadataout(wire_ram_block4a_3portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block4a_3.clk0_core_clock_enable = "ena0",
		ram_block4a_3.clk0_input_clock_enable = "ena0",
		ram_block4a_3.connectivity_checking = "OFF",
		ram_block4a_3.init_file = "fp_div_syn.hex",
		ram_block4a_3.init_file_layout = "port_a",
		ram_block4a_3.logical_ram_name = "ALTSYNCRAM",
		ram_block4a_3.mem_init0 = 512'h0000FFFF0003FFF8001FFF0007FFC001FFE001FFC007FF001FF801FF801FF007FC01FF00FF00FF00FE01FC07F01F80FC0FC0FC0FC1F83E07C1F0F83C1E0F0F0F,
		ram_block4a_3.operation_mode = "rom",
		ram_block4a_3.port_a_address_width = 9,
		ram_block4a_3.port_a_data_out_clear = "none",
		ram_block4a_3.port_a_data_out_clock = "none",
		ram_block4a_3.port_a_data_width = 1,
		ram_block4a_3.port_a_first_address = 0,
		ram_block4a_3.port_a_first_bit_number = 3,
		ram_block4a_3.port_a_last_address = 511,
		ram_block4a_3.port_a_logical_ram_depth = 512,
		ram_block4a_3.port_a_logical_ram_width = 9,
		ram_block4a_3.ram_block_type = "AUTO",
		ram_block4a_3.lpm_type = "cycloneiii_ram_block";
	cycloneiii_ram_block   ram_block4a_4
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[8:0]}),
	.portadataout(wire_ram_block4a_4portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block4a_4.clk0_core_clock_enable = "ena0",
		ram_block4a_4.clk0_input_clock_enable = "ena0",
		ram_block4a_4.connectivity_checking = "OFF",
		ram_block4a_4.init_file = "fp_div_syn.hex",
		ram_block4a_4.init_file_layout = "port_a",
		ram_block4a_4.logical_ram_name = "ALTSYNCRAM",
		ram_block4a_4.mem_init0 = 512'h00000000FFFFFFF8000000FFFFFFC000001FFFFFC00000FFFFF800007FFFF00003FFFF0000FFFF0001FFFC000FFF8003FFC003FFC007FE003FF007FC01FF00FF,
		ram_block4a_4.operation_mode = "rom",
		ram_block4a_4.port_a_address_width = 9,
		ram_block4a_4.port_a_data_out_clear = "none",
		ram_block4a_4.port_a_data_out_clock = "none",
		ram_block4a_4.port_a_data_width = 1,
		ram_block4a_4.port_a_first_address = 0,
		ram_block4a_4.port_a_first_bit_number = 4,
		ram_block4a_4.port_a_last_address = 511,
		ram_block4a_4.port_a_logical_ram_depth = 512,
		ram_block4a_4.port_a_logical_ram_width = 9,
		ram_block4a_4.ram_block_type = "AUTO",
		ram_block4a_4.lpm_type = "cycloneiii_ram_block";
	cycloneiii_ram_block   ram_block4a_5
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[8:0]}),
	.portadataout(wire_ram_block4a_5portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block4a_5.clk0_core_clock_enable = "ena0",
		ram_block4a_5.clk0_input_clock_enable = "ena0",
		ram_block4a_5.connectivity_checking = "OFF",
		ram_block4a_5.init_file = "fp_div_syn.hex",
		ram_block4a_5.init_file_layout = "port_a",
		ram_block4a_5.logical_ram_name = "ALTSYNCRAM",
		ram_block4a_5.mem_init0 = 512'h0000000000000007FFFFFFFFFFFFC000000000003FFFFFFFFFF8000000000FFFFFFFFF00000000FFFFFFFC0000007FFFFFC000003FFFFE00000FFFFC0000FFFF,
		ram_block4a_5.operation_mode = "rom",
		ram_block4a_5.port_a_address_width = 9,
		ram_block4a_5.port_a_data_out_clear = "none",
		ram_block4a_5.port_a_data_out_clock = "none",
		ram_block4a_5.port_a_data_width = 1,
		ram_block4a_5.port_a_first_address = 0,
		ram_block4a_5.port_a_first_bit_number = 5,
		ram_block4a_5.port_a_last_address = 511,
		ram_block4a_5.port_a_logical_ram_depth = 512,
		ram_block4a_5.port_a_logical_ram_width = 9,
		ram_block4a_5.ram_block_type = "AUTO",
		ram_block4a_5.lpm_type = "cycloneiii_ram_block";
	cycloneiii_ram_block   ram_block4a_6
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[8:0]}),
	.portadataout(wire_ram_block4a_6portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block4a_6.clk0_core_clock_enable = "ena0",
		ram_block4a_6.clk0_input_clock_enable = "ena0",
		ram_block4a_6.connectivity_checking = "OFF",
		ram_block4a_6.init_file = "fp_div_syn.hex",
		ram_block4a_6.init_file_layout = "port_a",
		ram_block4a_6.logical_ram_name = "ALTSYNCRAM",
		ram_block4a_6.mem_init0 = 512'h00000000000000000000000000003FFFFFFFFFFFFFFFFFFFFFF8000000000000000000FFFFFFFFFFFFFFFC0000000000003FFFFFFFFFFE0000000003FFFFFFFF,
		ram_block4a_6.operation_mode = "rom",
		ram_block4a_6.port_a_address_width = 9,
		ram_block4a_6.port_a_data_out_clear = "none",
		ram_block4a_6.port_a_data_out_clock = "none",
		ram_block4a_6.port_a_data_width = 1,
		ram_block4a_6.port_a_first_address = 0,
		ram_block4a_6.port_a_first_bit_number = 6,
		ram_block4a_6.port_a_last_address = 511,
		ram_block4a_6.port_a_logical_ram_depth = 512,
		ram_block4a_6.port_a_logical_ram_width = 9,
		ram_block4a_6.ram_block_type = "AUTO",
		ram_block4a_6.lpm_type = "cycloneiii_ram_block";
	cycloneiii_ram_block   ram_block4a_7
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[8:0]}),
	.portadataout(wire_ram_block4a_7portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block4a_7.clk0_core_clock_enable = "ena0",
		ram_block4a_7.clk0_input_clock_enable = "ena0",
		ram_block4a_7.connectivity_checking = "OFF",
		ram_block4a_7.init_file = "fp_div_syn.hex",
		ram_block4a_7.init_file_layout = "port_a",
		ram_block4a_7.logical_ram_name = "ALTSYNCRAM",
		ram_block4a_7.mem_init0 = 512'h0000000000000000000000000000000000000000000000000007FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC000000000000000000000001FFFFFFFFFFFFFFFFFF,
		ram_block4a_7.operation_mode = "rom",
		ram_block4a_7.port_a_address_width = 9,
		ram_block4a_7.port_a_data_out_clear = "none",
		ram_block4a_7.port_a_data_out_clock = "none",
		ram_block4a_7.port_a_data_width = 1,
		ram_block4a_7.port_a_first_address = 0,
		ram_block4a_7.port_a_first_bit_number = 7,
		ram_block4a_7.port_a_last_address = 511,
		ram_block4a_7.port_a_logical_ram_depth = 512,
		ram_block4a_7.port_a_logical_ram_width = 9,
		ram_block4a_7.ram_block_type = "AUTO",
		ram_block4a_7.lpm_type = "cycloneiii_ram_block";
	cycloneiii_ram_block   ram_block4a_8
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[8:0]}),
	.portadataout(wire_ram_block4a_8portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block4a_8.clk0_core_clock_enable = "ena0",
		ram_block4a_8.clk0_input_clock_enable = "ena0",
		ram_block4a_8.connectivity_checking = "OFF",
		ram_block4a_8.init_file = "fp_div_syn.hex",
		ram_block4a_8.init_file_layout = "port_a",
		ram_block4a_8.logical_ram_name = "ALTSYNCRAM",
		ram_block4a_8.mem_init0 = 512'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000003FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,
		ram_block4a_8.operation_mode = "rom",
		ram_block4a_8.port_a_address_width = 9,
		ram_block4a_8.port_a_data_out_clear = "none",
		ram_block4a_8.port_a_data_out_clock = "none",
		ram_block4a_8.port_a_data_width = 1,
		ram_block4a_8.port_a_first_address = 0,
		ram_block4a_8.port_a_first_bit_number = 8,
		ram_block4a_8.port_a_last_address = 511,
		ram_block4a_8.port_a_logical_ram_depth = 512,
		ram_block4a_8.port_a_logical_ram_width = 9,
		ram_block4a_8.ram_block_type = "AUTO",
		ram_block4a_8.lpm_type = "cycloneiii_ram_block";
	assign
		address_a_wire = address_a,
		q_a = {wire_ram_block4a_8portadataout[0], wire_ram_block4a_7portadataout[0], wire_ram_block4a_6portadataout[0], wire_ram_block4a_5portadataout[0], wire_ram_block4a_4portadataout[0], wire_ram_block4a_3portadataout[0], wire_ram_block4a_2portadataout[0], wire_ram_block4a_1portadataout[0], wire_ram_block4a_0portadataout[0]};
endmodule //fp_div_altsyncram


//lpm_add_sub DEVICE_FAMILY="Cyclone III" LPM_DIRECTION="ADD" LPM_PIPELINE=1 LPM_REPRESENTATION="SIGNED" LPM_WIDTH=9 aclr clken clock dataa datab overflow result
//VERSION_BEGIN 12.0 cbx_cycloneii 2012:05:31:20:08:02:SJ cbx_lpm_add_sub 2012:05:31:20:08:02:SJ cbx_mgl 2012:05:31:20:10:16:SJ cbx_stratix 2012:05:31:20:08:02:SJ cbx_stratixii 2012:05:31:20:08:02:SJ  VERSION_END


//lpm_add_sub DEVICE_FAMILY="Cyclone III" LPM_DIRECTION="SUB" LPM_PIPELINE=1 LPM_REPRESENTATION="SIGNED" LPM_WIDTH=9 aclr clken clock dataa datab result
//VERSION_BEGIN 12.0 cbx_cycloneii 2012:05:31:20:08:02:SJ cbx_lpm_add_sub 2012:05:31:20:08:02:SJ cbx_mgl 2012:05:31:20:10:16:SJ cbx_stratix 2012:05:31:20:08:02:SJ cbx_stratixii 2012:05:31:20:08:02:SJ  VERSION_END


//lpm_add_sub DEVICE_FAMILY="Cyclone III" LPM_DIRECTION="ADD" LPM_REPRESENTATION="UNSIGNED" LPM_WIDTH=31 cin dataa datab result
//VERSION_BEGIN 12.0 cbx_cycloneii 2012:05:31:20:08:02:SJ cbx_lpm_add_sub 2012:05:31:20:08:02:SJ cbx_mgl 2012:05:31:20:10:16:SJ cbx_stratix 2012:05:31:20:08:02:SJ cbx_stratixii 2012:05:31:20:08:02:SJ  VERSION_END


//lpm_add_sub DEVICE_FAMILY="Cyclone III" LPM_DIRECTION="SUB" LPM_REPRESENTATION="UNSIGNED" LPM_WIDTH=50 dataa datab result
//VERSION_BEGIN 12.0 cbx_cycloneii 2012:05:31:20:08:02:SJ cbx_lpm_add_sub 2012:05:31:20:08:02:SJ cbx_mgl 2012:05:31:20:10:16:SJ cbx_stratix 2012:05:31:20:08:02:SJ cbx_stratixii 2012:05:31:20:08:02:SJ  VERSION_END


//lpm_compare DEVICE_FAMILY="Cyclone III" LPM_REPRESENTATION="UNSIGNED" LPM_WIDTH=23 alb dataa datab
//VERSION_BEGIN 12.0 cbx_cycloneii 2012:05:31:20:08:02:SJ cbx_lpm_add_sub 2012:05:31:20:08:02:SJ cbx_lpm_compare 2012:05:31:20:08:02:SJ cbx_mgl 2012:05:31:20:10:16:SJ cbx_stratix 2012:05:31:20:08:02:SJ cbx_stratixii 2012:05:31:20:08:02:SJ  VERSION_END


//lpm_mult DEDICATED_MULTIPLIER_CIRCUITRY="YES" DEVICE_FAMILY="Cyclone III" LPM_PIPELINE=1 LPM_REPRESENTATION="UNSIGNED" LPM_WIDTHA=25 LPM_WIDTHB=10 LPM_WIDTHP=35 aclr clken clock dataa datab result
//VERSION_BEGIN 12.0 cbx_cycloneii 2012:05:31:20:08:02:SJ cbx_lpm_add_sub 2012:05:31:20:08:02:SJ cbx_lpm_mult 2012:05:31:20:08:02:SJ cbx_mgl 2012:05:31:20:10:16:SJ cbx_padd 2012:05:31:20:08:02:SJ cbx_stratix 2012:05:31:20:08:02:SJ cbx_stratixii 2012:05:31:20:08:02:SJ cbx_util_mgl 2012:05:31:20:08:02:SJ  VERSION_END


//adder DEVICE_FAMILY="Cyclone III" WIDTH=18 dataa datab result
//VERSION_BEGIN 12.0 cbx_mgl 2012:05:31:20:10:16:SJ cbx_stratixii 2012:05:31:20:08:02:SJ cbx_util_mgl 2012:05:31:20:08:02:SJ  VERSION_END

//synthesis_resources = dsp_9bit 4 lut 18 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  fp_div_mult
	( 
	aclr,
	clken,
	clock,
	dataa,
	datab,
	result) /* synthesis synthesis_clearbox=1 */;
	input   aclr;
	input   clken;
	input   clock;
	input   [24:0]  dataa;
	input   [9:0]  datab;
	output   [34:0]  result;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   aclr;
	tri1   clken;
	tri0   clock;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire	[17:0]	wire_add9_result;
	wire  [27:0]   wire_mac_mult5_dataout;
	wire  [16:0]   wire_mac_mult7_dataout;
	wire  [27:0]   wire_mac_out6_dataout;
	wire  [16:0]   wire_mac_out8_dataout;
	wire  [17:0]   wire_sft10a_in;
	wire  [17:0]   wire_sft10a_out;
	wire  [17:0]   wire_sft11a_in;
	wire  [17:0]   wire_sft11a_out;
	wire  [17:0]   wire_sft12a_in;
	wire  [17:0]   wire_sft12a_out;
	wire  w576w;
	wire  [35:0]  w649w;

	assign
		wire_add9_result = wire_sft10a_out + wire_sft11a_out;
	cycloneiii_mac_mult   mac_mult5
	( 
	.dataa({dataa[17:0]}),
	.datab({datab[9:0]}),
	.dataout(wire_mac_mult5_dataout),
	.signa(1'b0),
	.signb(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.aclr(1'b0),
	.clk(1'b1),
	.ena(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		mac_mult5.dataa_clock = "none",
		mac_mult5.dataa_width = 18,
		mac_mult5.datab_clock = "none",
		mac_mult5.datab_width = 10,
		mac_mult5.signa_clock = "none",
		mac_mult5.signb_clock = "none",
		mac_mult5.lpm_type = "cycloneiii_mac_mult";
	cycloneiii_mac_mult   mac_mult7
	( 
	.dataa({dataa[24:18]}),
	.datab({datab[9:0]}),
	.dataout(wire_mac_mult7_dataout),
	.signa(1'b0),
	.signb(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.aclr(1'b0),
	.clk(1'b1),
	.ena(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		mac_mult7.dataa_clock = "none",
		mac_mult7.dataa_width = 7,
		mac_mult7.datab_clock = "none",
		mac_mult7.datab_width = 10,
		mac_mult7.signa_clock = "none",
		mac_mult7.signb_clock = "none",
		mac_mult7.lpm_type = "cycloneiii_mac_mult";
	cycloneiii_mac_out   mac_out6
	( 
	.aclr(aclr),
	.clk(clock),
	.dataa(wire_mac_mult5_dataout),
	.dataout(wire_mac_out6_dataout),
	.ena(clken)
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		mac_out6.dataa_width = 28,
		mac_out6.output_clock = "0",
		mac_out6.lpm_type = "cycloneiii_mac_out";
	cycloneiii_mac_out   mac_out8
	( 
	.aclr(aclr),
	.clk(clock),
	.dataa(wire_mac_mult7_dataout),
	.dataout(wire_mac_out8_dataout),
	.ena(clken)
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		mac_out8.dataa_width = 17,
		mac_out8.output_clock = "0",
		mac_out8.lpm_type = "cycloneiii_mac_out";
	soft   sft10a_0
	( 
	.in(wire_sft10a_in[0:0]),
	.out(wire_sft10a_out[0:0]));
	soft   sft10a_1
	( 
	.in(wire_sft10a_in[1:1]),
	.out(wire_sft10a_out[1:1]));
	soft   sft10a_2
	( 
	.in(wire_sft10a_in[2:2]),
	.out(wire_sft10a_out[2:2]));
	soft   sft10a_3
	( 
	.in(wire_sft10a_in[3:3]),
	.out(wire_sft10a_out[3:3]));
	soft   sft10a_4
	( 
	.in(wire_sft10a_in[4:4]),
	.out(wire_sft10a_out[4:4]));
	soft   sft10a_5
	( 
	.in(wire_sft10a_in[5:5]),
	.out(wire_sft10a_out[5:5]));
	soft   sft10a_6
	( 
	.in(wire_sft10a_in[6:6]),
	.out(wire_sft10a_out[6:6]));
	soft   sft10a_7
	( 
	.in(wire_sft10a_in[7:7]),
	.out(wire_sft10a_out[7:7]));
	soft   sft10a_8
	( 
	.in(wire_sft10a_in[8:8]),
	.out(wire_sft10a_out[8:8]));
	soft   sft10a_9
	( 
	.in(wire_sft10a_in[9:9]),
	.out(wire_sft10a_out[9:9]));
	soft   sft10a_10
	( 
	.in(wire_sft10a_in[10:10]),
	.out(wire_sft10a_out[10:10]));
	soft   sft10a_11
	( 
	.in(wire_sft10a_in[11:11]),
	.out(wire_sft10a_out[11:11]));
	soft   sft10a_12
	( 
	.in(wire_sft10a_in[12:12]),
	.out(wire_sft10a_out[12:12]));
	soft   sft10a_13
	( 
	.in(wire_sft10a_in[13:13]),
	.out(wire_sft10a_out[13:13]));
	soft   sft10a_14
	( 
	.in(wire_sft10a_in[14:14]),
	.out(wire_sft10a_out[14:14]));
	soft   sft10a_15
	( 
	.in(wire_sft10a_in[15:15]),
	.out(wire_sft10a_out[15:15]));
	soft   sft10a_16
	( 
	.in(wire_sft10a_in[16:16]),
	.out(wire_sft10a_out[16:16]));
	soft   sft10a_17
	( 
	.in(wire_sft10a_in[17:17]),
	.out(wire_sft10a_out[17:17]));
	assign
		wire_sft10a_in = {w576w, {wire_mac_out8_dataout[16], {wire_mac_out8_dataout[15], {wire_mac_out8_dataout[14], {wire_mac_out8_dataout[13], {wire_mac_out8_dataout[12], {wire_mac_out8_dataout[11], {wire_mac_out8_dataout[10], {wire_mac_out6_dataout[27], {wire_mac_out6_dataout[26], {wire_mac_out6_dataout[25], {wire_mac_out6_dataout[24], {wire_mac_out6_dataout[23], {wire_mac_out6_dataout[22], {wire_mac_out6_dataout[21], {wire_mac_out6_dataout[20], {wire_mac_out6_dataout[19:18]}}}}}}}}}}}}}}}}};
	soft   sft11a_0
	( 
	.in(wire_sft11a_in[0:0]),
	.out(wire_sft11a_out[0:0]));
	soft   sft11a_1
	( 
	.in(wire_sft11a_in[1:1]),
	.out(wire_sft11a_out[1:1]));
	soft   sft11a_2
	( 
	.in(wire_sft11a_in[2:2]),
	.out(wire_sft11a_out[2:2]));
	soft   sft11a_3
	( 
	.in(wire_sft11a_in[3:3]),
	.out(wire_sft11a_out[3:3]));
	soft   sft11a_4
	( 
	.in(wire_sft11a_in[4:4]),
	.out(wire_sft11a_out[4:4]));
	soft   sft11a_5
	( 
	.in(wire_sft11a_in[5:5]),
	.out(wire_sft11a_out[5:5]));
	soft   sft11a_6
	( 
	.in(wire_sft11a_in[6:6]),
	.out(wire_sft11a_out[6:6]));
	soft   sft11a_7
	( 
	.in(wire_sft11a_in[7:7]),
	.out(wire_sft11a_out[7:7]));
	soft   sft11a_8
	( 
	.in(wire_sft11a_in[8:8]),
	.out(wire_sft11a_out[8:8]));
	soft   sft11a_9
	( 
	.in(wire_sft11a_in[9:9]),
	.out(wire_sft11a_out[9:9]));
	soft   sft11a_10
	( 
	.in(wire_sft11a_in[10:10]),
	.out(wire_sft11a_out[10:10]));
	soft   sft11a_11
	( 
	.in(wire_sft11a_in[11:11]),
	.out(wire_sft11a_out[11:11]));
	soft   sft11a_12
	( 
	.in(wire_sft11a_in[12:12]),
	.out(wire_sft11a_out[12:12]));
	soft   sft11a_13
	( 
	.in(wire_sft11a_in[13:13]),
	.out(wire_sft11a_out[13:13]));
	soft   sft11a_14
	( 
	.in(wire_sft11a_in[14:14]),
	.out(wire_sft11a_out[14:14]));
	soft   sft11a_15
	( 
	.in(wire_sft11a_in[15:15]),
	.out(wire_sft11a_out[15:15]));
	soft   sft11a_16
	( 
	.in(wire_sft11a_in[16:16]),
	.out(wire_sft11a_out[16:16]));
	soft   sft11a_17
	( 
	.in(wire_sft11a_in[17:17]),
	.out(wire_sft11a_out[17:17]));
	assign
		wire_sft11a_in = {w576w, {w576w, {w576w, {w576w, {w576w, {w576w, {w576w, {w576w, {wire_mac_out8_dataout[9], {wire_mac_out8_dataout[8], {wire_mac_out8_dataout[7], {wire_mac_out8_dataout[6], {wire_mac_out8_dataout[5], {wire_mac_out8_dataout[4], {wire_mac_out8_dataout[3], {wire_mac_out8_dataout[2], {wire_mac_out8_dataout[1:0]}}}}}}}}}}}}}}}}};
	soft   sft12a_0
	( 
	.in(wire_sft12a_in[0:0]),
	.out(wire_sft12a_out[0:0]));
	soft   sft12a_1
	( 
	.in(wire_sft12a_in[1:1]),
	.out(wire_sft12a_out[1:1]));
	soft   sft12a_2
	( 
	.in(wire_sft12a_in[2:2]),
	.out(wire_sft12a_out[2:2]));
	soft   sft12a_3
	( 
	.in(wire_sft12a_in[3:3]),
	.out(wire_sft12a_out[3:3]));
	soft   sft12a_4
	( 
	.in(wire_sft12a_in[4:4]),
	.out(wire_sft12a_out[4:4]));
	soft   sft12a_5
	( 
	.in(wire_sft12a_in[5:5]),
	.out(wire_sft12a_out[5:5]));
	soft   sft12a_6
	( 
	.in(wire_sft12a_in[6:6]),
	.out(wire_sft12a_out[6:6]));
	soft   sft12a_7
	( 
	.in(wire_sft12a_in[7:7]),
	.out(wire_sft12a_out[7:7]));
	soft   sft12a_8
	( 
	.in(wire_sft12a_in[8:8]),
	.out(wire_sft12a_out[8:8]));
	soft   sft12a_9
	( 
	.in(wire_sft12a_in[9:9]),
	.out(wire_sft12a_out[9:9]));
	soft   sft12a_10
	( 
	.in(wire_sft12a_in[10:10]),
	.out(wire_sft12a_out[10:10]));
	soft   sft12a_11
	( 
	.in(wire_sft12a_in[11:11]),
	.out(wire_sft12a_out[11:11]));
	soft   sft12a_12
	( 
	.in(wire_sft12a_in[12:12]),
	.out(wire_sft12a_out[12:12]));
	soft   sft12a_13
	( 
	.in(wire_sft12a_in[13:13]),
	.out(wire_sft12a_out[13:13]));
	soft   sft12a_14
	( 
	.in(wire_sft12a_in[14:14]),
	.out(wire_sft12a_out[14:14]));
	soft   sft12a_15
	( 
	.in(wire_sft12a_in[15:15]),
	.out(wire_sft12a_out[15:15]));
	soft   sft12a_16
	( 
	.in(wire_sft12a_in[16:16]),
	.out(wire_sft12a_out[16:16]));
	soft   sft12a_17
	( 
	.in(wire_sft12a_in[17:17]),
	.out(wire_sft12a_out[17:17]));
	assign
		wire_sft12a_in = wire_add9_result;
	assign
		result = w649w[34:0],
		w576w = 1'b0,
		w649w = {wire_sft12a_out[17:16], wire_sft12a_out[15:14], wire_sft12a_out[13:12], wire_sft12a_out[11:10], wire_sft12a_out[9:8], wire_sft12a_out[7:6], wire_sft12a_out[5:4], wire_sft12a_out[3:2], wire_sft12a_out[1:0], wire_mac_out6_dataout[17], wire_mac_out6_dataout[16], wire_mac_out6_dataout[15], wire_mac_out6_dataout[14], wire_mac_out6_dataout[13], wire_mac_out6_dataout[12], wire_mac_out6_dataout[11], wire_mac_out6_dataout[10], wire_mac_out6_dataout[9], wire_mac_out6_dataout[8], wire_mac_out6_dataout[7], wire_mac_out6_dataout[6], wire_mac_out6_dataout[5], wire_mac_out6_dataout[4], wire_mac_out6_dataout[3], wire_mac_out6_dataout[2], wire_mac_out6_dataout[1], wire_mac_out6_dataout[0]};
endmodule //fp_div_mult


//lpm_mult DEDICATED_MULTIPLIER_CIRCUITRY="YES" DEVICE_FAMILY="Cyclone III" LPM_PIPELINE=1 LPM_REPRESENTATION="UNSIGNED" LPM_WIDTHA=24 LPM_WIDTHB=10 LPM_WIDTHP=34 aclr clken clock dataa datab result
//VERSION_BEGIN 12.0 cbx_cycloneii 2012:05:31:20:08:02:SJ cbx_lpm_add_sub 2012:05:31:20:08:02:SJ cbx_lpm_mult 2012:05:31:20:08:02:SJ cbx_mgl 2012:05:31:20:10:16:SJ cbx_padd 2012:05:31:20:08:02:SJ cbx_stratix 2012:05:31:20:08:02:SJ cbx_stratixii 2012:05:31:20:08:02:SJ cbx_util_mgl 2012:05:31:20:08:02:SJ  VERSION_END


//adder DEVICE_FAMILY="Cyclone III" WIDTH=17 dataa datab result
//VERSION_BEGIN 12.0 cbx_mgl 2012:05:31:20:10:16:SJ cbx_stratixii 2012:05:31:20:08:02:SJ cbx_util_mgl 2012:05:31:20:08:02:SJ  VERSION_END

//synthesis_resources = dsp_9bit 4 lut 17 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  fp_div_mult1
	( 
	aclr,
	clken,
	clock,
	dataa,
	datab,
	result) /* synthesis synthesis_clearbox=1 */;
	input   aclr;
	input   clken;
	input   clock;
	input   [23:0]  dataa;
	input   [9:0]  datab;
	output   [33:0]  result;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   aclr;
	tri1   clken;
	tri0   clock;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire	[16:0]	wire_add17_result;
	wire  [27:0]   wire_mac_mult13_dataout;
	wire  [15:0]   wire_mac_mult15_dataout;
	wire  [27:0]   wire_mac_out14_dataout;
	wire  [15:0]   wire_mac_out16_dataout;
	wire  [16:0]   wire_sft18a_in;
	wire  [16:0]   wire_sft18a_out;
	wire  [16:0]   wire_sft19a_in;
	wire  [16:0]   wire_sft19a_out;
	wire  [16:0]   wire_sft20a_in;
	wire  [16:0]   wire_sft20a_out;
	wire  w791w;
	wire  [34:0]  w861w;

	assign
		wire_add17_result = wire_sft18a_out + wire_sft19a_out;
	cycloneiii_mac_mult   mac_mult13
	( 
	.dataa({dataa[17:0]}),
	.datab({datab[9:0]}),
	.dataout(wire_mac_mult13_dataout),
	.signa(1'b0),
	.signb(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.aclr(1'b0),
	.clk(1'b1),
	.ena(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		mac_mult13.dataa_clock = "none",
		mac_mult13.dataa_width = 18,
		mac_mult13.datab_clock = "none",
		mac_mult13.datab_width = 10,
		mac_mult13.signa_clock = "none",
		mac_mult13.signb_clock = "none",
		mac_mult13.lpm_type = "cycloneiii_mac_mult";
	cycloneiii_mac_mult   mac_mult15
	( 
	.dataa({dataa[23:18]}),
	.datab({datab[9:0]}),
	.dataout(wire_mac_mult15_dataout),
	.signa(1'b0),
	.signb(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.aclr(1'b0),
	.clk(1'b1),
	.ena(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		mac_mult15.dataa_clock = "none",
		mac_mult15.dataa_width = 6,
		mac_mult15.datab_clock = "none",
		mac_mult15.datab_width = 10,
		mac_mult15.signa_clock = "none",
		mac_mult15.signb_clock = "none",
		mac_mult15.lpm_type = "cycloneiii_mac_mult";
	cycloneiii_mac_out   mac_out14
	( 
	.aclr(aclr),
	.clk(clock),
	.dataa(wire_mac_mult13_dataout),
	.dataout(wire_mac_out14_dataout),
	.ena(clken)
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		mac_out14.dataa_width = 28,
		mac_out14.output_clock = "0",
		mac_out14.lpm_type = "cycloneiii_mac_out";
	cycloneiii_mac_out   mac_out16
	( 
	.aclr(aclr),
	.clk(clock),
	.dataa(wire_mac_mult15_dataout),
	.dataout(wire_mac_out16_dataout),
	.ena(clken)
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		mac_out16.dataa_width = 16,
		mac_out16.output_clock = "0",
		mac_out16.lpm_type = "cycloneiii_mac_out";
	soft   sft18a_0
	( 
	.in(wire_sft18a_in[0:0]),
	.out(wire_sft18a_out[0:0]));
	soft   sft18a_1
	( 
	.in(wire_sft18a_in[1:1]),
	.out(wire_sft18a_out[1:1]));
	soft   sft18a_2
	( 
	.in(wire_sft18a_in[2:2]),
	.out(wire_sft18a_out[2:2]));
	soft   sft18a_3
	( 
	.in(wire_sft18a_in[3:3]),
	.out(wire_sft18a_out[3:3]));
	soft   sft18a_4
	( 
	.in(wire_sft18a_in[4:4]),
	.out(wire_sft18a_out[4:4]));
	soft   sft18a_5
	( 
	.in(wire_sft18a_in[5:5]),
	.out(wire_sft18a_out[5:5]));
	soft   sft18a_6
	( 
	.in(wire_sft18a_in[6:6]),
	.out(wire_sft18a_out[6:6]));
	soft   sft18a_7
	( 
	.in(wire_sft18a_in[7:7]),
	.out(wire_sft18a_out[7:7]));
	soft   sft18a_8
	( 
	.in(wire_sft18a_in[8:8]),
	.out(wire_sft18a_out[8:8]));
	soft   sft18a_9
	( 
	.in(wire_sft18a_in[9:9]),
	.out(wire_sft18a_out[9:9]));
	soft   sft18a_10
	( 
	.in(wire_sft18a_in[10:10]),
	.out(wire_sft18a_out[10:10]));
	soft   sft18a_11
	( 
	.in(wire_sft18a_in[11:11]),
	.out(wire_sft18a_out[11:11]));
	soft   sft18a_12
	( 
	.in(wire_sft18a_in[12:12]),
	.out(wire_sft18a_out[12:12]));
	soft   sft18a_13
	( 
	.in(wire_sft18a_in[13:13]),
	.out(wire_sft18a_out[13:13]));
	soft   sft18a_14
	( 
	.in(wire_sft18a_in[14:14]),
	.out(wire_sft18a_out[14:14]));
	soft   sft18a_15
	( 
	.in(wire_sft18a_in[15:15]),
	.out(wire_sft18a_out[15:15]));
	soft   sft18a_16
	( 
	.in(wire_sft18a_in[16:16]),
	.out(wire_sft18a_out[16:16]));
	assign
		wire_sft18a_in = {w791w, {wire_mac_out16_dataout[15], {wire_mac_out16_dataout[14], {wire_mac_out16_dataout[13], {wire_mac_out16_dataout[12], {wire_mac_out16_dataout[11], {wire_mac_out16_dataout[10], {wire_mac_out14_dataout[27], {wire_mac_out14_dataout[26], {wire_mac_out14_dataout[25], {wire_mac_out14_dataout[24], {wire_mac_out14_dataout[23], {wire_mac_out14_dataout[22], {wire_mac_out14_dataout[21], {wire_mac_out14_dataout[20], {wire_mac_out14_dataout[19:18]}}}}}}}}}}}}}}}};
	soft   sft19a_0
	( 
	.in(wire_sft19a_in[0:0]),
	.out(wire_sft19a_out[0:0]));
	soft   sft19a_1
	( 
	.in(wire_sft19a_in[1:1]),
	.out(wire_sft19a_out[1:1]));
	soft   sft19a_2
	( 
	.in(wire_sft19a_in[2:2]),
	.out(wire_sft19a_out[2:2]));
	soft   sft19a_3
	( 
	.in(wire_sft19a_in[3:3]),
	.out(wire_sft19a_out[3:3]));
	soft   sft19a_4
	( 
	.in(wire_sft19a_in[4:4]),
	.out(wire_sft19a_out[4:4]));
	soft   sft19a_5
	( 
	.in(wire_sft19a_in[5:5]),
	.out(wire_sft19a_out[5:5]));
	soft   sft19a_6
	( 
	.in(wire_sft19a_in[6:6]),
	.out(wire_sft19a_out[6:6]));
	soft   sft19a_7
	( 
	.in(wire_sft19a_in[7:7]),
	.out(wire_sft19a_out[7:7]));
	soft   sft19a_8
	( 
	.in(wire_sft19a_in[8:8]),
	.out(wire_sft19a_out[8:8]));
	soft   sft19a_9
	( 
	.in(wire_sft19a_in[9:9]),
	.out(wire_sft19a_out[9:9]));
	soft   sft19a_10
	( 
	.in(wire_sft19a_in[10:10]),
	.out(wire_sft19a_out[10:10]));
	soft   sft19a_11
	( 
	.in(wire_sft19a_in[11:11]),
	.out(wire_sft19a_out[11:11]));
	soft   sft19a_12
	( 
	.in(wire_sft19a_in[12:12]),
	.out(wire_sft19a_out[12:12]));
	soft   sft19a_13
	( 
	.in(wire_sft19a_in[13:13]),
	.out(wire_sft19a_out[13:13]));
	soft   sft19a_14
	( 
	.in(wire_sft19a_in[14:14]),
	.out(wire_sft19a_out[14:14]));
	soft   sft19a_15
	( 
	.in(wire_sft19a_in[15:15]),
	.out(wire_sft19a_out[15:15]));
	soft   sft19a_16
	( 
	.in(wire_sft19a_in[16:16]),
	.out(wire_sft19a_out[16:16]));
	assign
		wire_sft19a_in = {w791w, {w791w, {w791w, {w791w, {w791w, {w791w, {w791w, {wire_mac_out16_dataout[9], {wire_mac_out16_dataout[8], {wire_mac_out16_dataout[7], {wire_mac_out16_dataout[6], {wire_mac_out16_dataout[5], {wire_mac_out16_dataout[4], {wire_mac_out16_dataout[3], {wire_mac_out16_dataout[2], {wire_mac_out16_dataout[1:0]}}}}}}}}}}}}}}}};
	soft   sft20a_0
	( 
	.in(wire_sft20a_in[0:0]),
	.out(wire_sft20a_out[0:0]));
	soft   sft20a_1
	( 
	.in(wire_sft20a_in[1:1]),
	.out(wire_sft20a_out[1:1]));
	soft   sft20a_2
	( 
	.in(wire_sft20a_in[2:2]),
	.out(wire_sft20a_out[2:2]));
	soft   sft20a_3
	( 
	.in(wire_sft20a_in[3:3]),
	.out(wire_sft20a_out[3:3]));
	soft   sft20a_4
	( 
	.in(wire_sft20a_in[4:4]),
	.out(wire_sft20a_out[4:4]));
	soft   sft20a_5
	( 
	.in(wire_sft20a_in[5:5]),
	.out(wire_sft20a_out[5:5]));
	soft   sft20a_6
	( 
	.in(wire_sft20a_in[6:6]),
	.out(wire_sft20a_out[6:6]));
	soft   sft20a_7
	( 
	.in(wire_sft20a_in[7:7]),
	.out(wire_sft20a_out[7:7]));
	soft   sft20a_8
	( 
	.in(wire_sft20a_in[8:8]),
	.out(wire_sft20a_out[8:8]));
	soft   sft20a_9
	( 
	.in(wire_sft20a_in[9:9]),
	.out(wire_sft20a_out[9:9]));
	soft   sft20a_10
	( 
	.in(wire_sft20a_in[10:10]),
	.out(wire_sft20a_out[10:10]));
	soft   sft20a_11
	( 
	.in(wire_sft20a_in[11:11]),
	.out(wire_sft20a_out[11:11]));
	soft   sft20a_12
	( 
	.in(wire_sft20a_in[12:12]),
	.out(wire_sft20a_out[12:12]));
	soft   sft20a_13
	( 
	.in(wire_sft20a_in[13:13]),
	.out(wire_sft20a_out[13:13]));
	soft   sft20a_14
	( 
	.in(wire_sft20a_in[14:14]),
	.out(wire_sft20a_out[14:14]));
	soft   sft20a_15
	( 
	.in(wire_sft20a_in[15:15]),
	.out(wire_sft20a_out[15:15]));
	soft   sft20a_16
	( 
	.in(wire_sft20a_in[16:16]),
	.out(wire_sft20a_out[16:16]));
	assign
		wire_sft20a_in = wire_add17_result;
	assign
		result = w861w[33:0],
		w791w = 1'b0,
		w861w = {wire_sft20a_out[16:15], wire_sft20a_out[14:13], wire_sft20a_out[12:11], wire_sft20a_out[10:9], wire_sft20a_out[8:7], wire_sft20a_out[6:5], wire_sft20a_out[4:3], wire_sft20a_out[2:1], wire_sft20a_out[0], wire_mac_out14_dataout[17], wire_mac_out14_dataout[16], wire_mac_out14_dataout[15], wire_mac_out14_dataout[14], wire_mac_out14_dataout[13], wire_mac_out14_dataout[12], wire_mac_out14_dataout[11], wire_mac_out14_dataout[10], wire_mac_out14_dataout[9], wire_mac_out14_dataout[8], wire_mac_out14_dataout[7], wire_mac_out14_dataout[6], wire_mac_out14_dataout[5], wire_mac_out14_dataout[4], wire_mac_out14_dataout[3], wire_mac_out14_dataout[2], wire_mac_out14_dataout[1], wire_mac_out14_dataout[0]};
endmodule //fp_div_mult1


//lpm_mult DEDICATED_MULTIPLIER_CIRCUITRY="YES" DEVICE_FAMILY="Cyclone III" LPM_PIPELINE=1 LPM_REPRESENTATION="UNSIGNED" LPM_WIDTHA=17 LPM_WIDTHB=17 LPM_WIDTHP=34 aclr clken clock dataa datab result
//VERSION_BEGIN 12.0 cbx_cycloneii 2012:05:31:20:08:02:SJ cbx_lpm_add_sub 2012:05:31:20:08:02:SJ cbx_lpm_mult 2012:05:31:20:08:02:SJ cbx_mgl 2012:05:31:20:10:16:SJ cbx_padd 2012:05:31:20:08:02:SJ cbx_stratix 2012:05:31:20:08:02:SJ cbx_stratixii 2012:05:31:20:08:02:SJ cbx_util_mgl 2012:05:31:20:08:02:SJ  VERSION_END

//synthesis_resources = dsp_9bit 2 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  fp_div_mult12
	( 
	aclr,
	clken,
	clock,
	dataa,
	datab,
	result) /* synthesis synthesis_clearbox=1 */;
	input   aclr;
	input   clken;
	input   clock;
	input   [16:0]  dataa;
	input   [16:0]  datab;
	output   [33:0]  result;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   aclr;
	tri1   clken;
	tri0   clock;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [33:0]   wire_mac_mult21_dataout;
	wire  [33:0]   wire_mac_out22_dataout;

	cycloneiii_mac_mult   mac_mult21
	( 
	.dataa({dataa}),
	.datab({datab}),
	.dataout(wire_mac_mult21_dataout),
	.signa(1'b0),
	.signb(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.aclr(1'b0),
	.clk(1'b1),
	.ena(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		mac_mult21.dataa_clock = "none",
		mac_mult21.dataa_width = 17,
		mac_mult21.datab_clock = "none",
		mac_mult21.datab_width = 17,
		mac_mult21.signa_clock = "none",
		mac_mult21.signb_clock = "none",
		mac_mult21.lpm_type = "cycloneiii_mac_mult";
	cycloneiii_mac_out   mac_out22
	( 
	.aclr(aclr),
	.clk(clock),
	.dataa(wire_mac_mult21_dataout),
	.dataout(wire_mac_out22_dataout),
	.ena(clken)
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		mac_out22.dataa_width = 34,
		mac_out22.output_clock = "0",
		mac_out22.lpm_type = "cycloneiii_mac_out";
	assign
		result = wire_mac_out22_dataout[33:0];
endmodule //fp_div_mult12


//lpm_mult DEDICATED_MULTIPLIER_CIRCUITRY="YES" DEVICE_FAMILY="Cyclone III" LPM_PIPELINE=1 LPM_REPRESENTATION="UNSIGNED" LPM_WIDTHA=34 LPM_WIDTHB=17 LPM_WIDTHP=51 aclr clken clock dataa datab result
//VERSION_BEGIN 12.0 cbx_cycloneii 2012:05:31:20:08:02:SJ cbx_lpm_add_sub 2012:05:31:20:08:02:SJ cbx_lpm_mult 2012:05:31:20:08:02:SJ cbx_mgl 2012:05:31:20:10:16:SJ cbx_padd 2012:05:31:20:08:02:SJ cbx_stratix 2012:05:31:20:08:02:SJ cbx_stratixii 2012:05:31:20:08:02:SJ cbx_util_mgl 2012:05:31:20:08:02:SJ  VERSION_END


//adder DEVICE_FAMILY="Cyclone III" WIDTH=34 dataa datab result
//VERSION_BEGIN 12.0 cbx_mgl 2012:05:31:20:10:16:SJ cbx_stratixii 2012:05:31:20:08:02:SJ cbx_util_mgl 2012:05:31:20:08:02:SJ  VERSION_END

//synthesis_resources = dsp_9bit 4 lut 34 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  fp_div_mult123
	( 
	aclr,
	clken,
	clock,
	dataa,
	datab,
	result) /* synthesis synthesis_clearbox=1 */;
	input   aclr;
	input   clken;
	input   clock;
	input   [33:0]  dataa;
	input   [16:0]  datab;
	output   [50:0]  result;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   aclr;
	tri1   clken;
	tri0   clock;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire	[33:0]	wire_add27_result;
	wire  [34:0]   wire_mac_mult23_dataout;
	wire  [32:0]   wire_mac_mult25_dataout;
	wire  [34:0]   wire_mac_out24_dataout;
	wire  [32:0]   wire_mac_out26_dataout;
	wire  [33:0]   wire_sft28a_in;
	wire  [33:0]   wire_sft28a_out;
	wire  [33:0]   wire_sft29a_in;
	wire  [33:0]   wire_sft29a_out;
	wire  [33:0]   wire_sft30a_in;
	wire  [33:0]   wire_sft30a_out;
	wire  w1048w;
	wire  [51:0]  w1169w;

	assign
		wire_add27_result = wire_sft28a_out + wire_sft29a_out;
	cycloneiii_mac_mult   mac_mult23
	( 
	.dataa({dataa[17:0]}),
	.datab({datab[16:0]}),
	.dataout(wire_mac_mult23_dataout),
	.signa(1'b0),
	.signb(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.aclr(1'b0),
	.clk(1'b1),
	.ena(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		mac_mult23.dataa_clock = "none",
		mac_mult23.dataa_width = 18,
		mac_mult23.datab_clock = "none",
		mac_mult23.datab_width = 17,
		mac_mult23.signa_clock = "none",
		mac_mult23.signb_clock = "none",
		mac_mult23.lpm_type = "cycloneiii_mac_mult";
	cycloneiii_mac_mult   mac_mult25
	( 
	.dataa({dataa[33:18]}),
	.datab({datab[16:0]}),
	.dataout(wire_mac_mult25_dataout),
	.signa(1'b0),
	.signb(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.aclr(1'b0),
	.clk(1'b1),
	.ena(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		mac_mult25.dataa_clock = "none",
		mac_mult25.dataa_width = 16,
		mac_mult25.datab_clock = "none",
		mac_mult25.datab_width = 17,
		mac_mult25.signa_clock = "none",
		mac_mult25.signb_clock = "none",
		mac_mult25.lpm_type = "cycloneiii_mac_mult";
	cycloneiii_mac_out   mac_out24
	( 
	.aclr(aclr),
	.clk(clock),
	.dataa(wire_mac_mult23_dataout),
	.dataout(wire_mac_out24_dataout),
	.ena(clken)
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		mac_out24.dataa_width = 35,
		mac_out24.output_clock = "0",
		mac_out24.lpm_type = "cycloneiii_mac_out";
	cycloneiii_mac_out   mac_out26
	( 
	.aclr(aclr),
	.clk(clock),
	.dataa(wire_mac_mult25_dataout),
	.dataout(wire_mac_out26_dataout),
	.ena(clken)
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		mac_out26.dataa_width = 33,
		mac_out26.output_clock = "0",
		mac_out26.lpm_type = "cycloneiii_mac_out";
	soft   sft28a_0
	( 
	.in(wire_sft28a_in[0:0]),
	.out(wire_sft28a_out[0:0]));
	soft   sft28a_1
	( 
	.in(wire_sft28a_in[1:1]),
	.out(wire_sft28a_out[1:1]));
	soft   sft28a_2
	( 
	.in(wire_sft28a_in[2:2]),
	.out(wire_sft28a_out[2:2]));
	soft   sft28a_3
	( 
	.in(wire_sft28a_in[3:3]),
	.out(wire_sft28a_out[3:3]));
	soft   sft28a_4
	( 
	.in(wire_sft28a_in[4:4]),
	.out(wire_sft28a_out[4:4]));
	soft   sft28a_5
	( 
	.in(wire_sft28a_in[5:5]),
	.out(wire_sft28a_out[5:5]));
	soft   sft28a_6
	( 
	.in(wire_sft28a_in[6:6]),
	.out(wire_sft28a_out[6:6]));
	soft   sft28a_7
	( 
	.in(wire_sft28a_in[7:7]),
	.out(wire_sft28a_out[7:7]));
	soft   sft28a_8
	( 
	.in(wire_sft28a_in[8:8]),
	.out(wire_sft28a_out[8:8]));
	soft   sft28a_9
	( 
	.in(wire_sft28a_in[9:9]),
	.out(wire_sft28a_out[9:9]));
	soft   sft28a_10
	( 
	.in(wire_sft28a_in[10:10]),
	.out(wire_sft28a_out[10:10]));
	soft   sft28a_11
	( 
	.in(wire_sft28a_in[11:11]),
	.out(wire_sft28a_out[11:11]));
	soft   sft28a_12
	( 
	.in(wire_sft28a_in[12:12]),
	.out(wire_sft28a_out[12:12]));
	soft   sft28a_13
	( 
	.in(wire_sft28a_in[13:13]),
	.out(wire_sft28a_out[13:13]));
	soft   sft28a_14
	( 
	.in(wire_sft28a_in[14:14]),
	.out(wire_sft28a_out[14:14]));
	soft   sft28a_15
	( 
	.in(wire_sft28a_in[15:15]),
	.out(wire_sft28a_out[15:15]));
	soft   sft28a_16
	( 
	.in(wire_sft28a_in[16:16]),
	.out(wire_sft28a_out[16:16]));
	soft   sft28a_17
	( 
	.in(wire_sft28a_in[17:17]),
	.out(wire_sft28a_out[17:17]));
	soft   sft28a_18
	( 
	.in(wire_sft28a_in[18:18]),
	.out(wire_sft28a_out[18:18]));
	soft   sft28a_19
	( 
	.in(wire_sft28a_in[19:19]),
	.out(wire_sft28a_out[19:19]));
	soft   sft28a_20
	( 
	.in(wire_sft28a_in[20:20]),
	.out(wire_sft28a_out[20:20]));
	soft   sft28a_21
	( 
	.in(wire_sft28a_in[21:21]),
	.out(wire_sft28a_out[21:21]));
	soft   sft28a_22
	( 
	.in(wire_sft28a_in[22:22]),
	.out(wire_sft28a_out[22:22]));
	soft   sft28a_23
	( 
	.in(wire_sft28a_in[23:23]),
	.out(wire_sft28a_out[23:23]));
	soft   sft28a_24
	( 
	.in(wire_sft28a_in[24:24]),
	.out(wire_sft28a_out[24:24]));
	soft   sft28a_25
	( 
	.in(wire_sft28a_in[25:25]),
	.out(wire_sft28a_out[25:25]));
	soft   sft28a_26
	( 
	.in(wire_sft28a_in[26:26]),
	.out(wire_sft28a_out[26:26]));
	soft   sft28a_27
	( 
	.in(wire_sft28a_in[27:27]),
	.out(wire_sft28a_out[27:27]));
	soft   sft28a_28
	( 
	.in(wire_sft28a_in[28:28]),
	.out(wire_sft28a_out[28:28]));
	soft   sft28a_29
	( 
	.in(wire_sft28a_in[29:29]),
	.out(wire_sft28a_out[29:29]));
	soft   sft28a_30
	( 
	.in(wire_sft28a_in[30:30]),
	.out(wire_sft28a_out[30:30]));
	soft   sft28a_31
	( 
	.in(wire_sft28a_in[31:31]),
	.out(wire_sft28a_out[31:31]));
	soft   sft28a_32
	( 
	.in(wire_sft28a_in[32:32]),
	.out(wire_sft28a_out[32:32]));
	soft   sft28a_33
	( 
	.in(wire_sft28a_in[33:33]),
	.out(wire_sft28a_out[33:33]));
	assign
		wire_sft28a_in = {w1048w, {wire_mac_out26_dataout[32], {wire_mac_out26_dataout[31], {wire_mac_out26_dataout[30], {wire_mac_out26_dataout[29], {wire_mac_out26_dataout[28], {wire_mac_out26_dataout[27], {wire_mac_out26_dataout[26], {wire_mac_out26_dataout[25], {wire_mac_out26_dataout[24], {wire_mac_out26_dataout[23], {wire_mac_out26_dataout[22], {wire_mac_out26_dataout[21], {wire_mac_out26_dataout[20], {wire_mac_out26_dataout[19], {wire_mac_out26_dataout[18], {wire_mac_out26_dataout[17], {wire_mac_out24_dataout[34], {wire_mac_out24_dataout[33], {wire_mac_out24_dataout[32], {wire_mac_out24_dataout[31], {wire_mac_out24_dataout[30], {wire_mac_out24_dataout[29], {wire_mac_out24_dataout[28], {wire_mac_out24_dataout[27], {wire_mac_out24_dataout[26], {wire_mac_out24_dataout[25], {wire_mac_out24_dataout[24], {wire_mac_out24_dataout[23], {wire_mac_out24_dataout[22], {wire_mac_out24_dataout[21], {wire_mac_out24_dataout[20], {wire_mac_out24_dataout[19:18]}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}};
	soft   sft29a_0
	( 
	.in(wire_sft29a_in[0:0]),
	.out(wire_sft29a_out[0:0]));
	soft   sft29a_1
	( 
	.in(wire_sft29a_in[1:1]),
	.out(wire_sft29a_out[1:1]));
	soft   sft29a_2
	( 
	.in(wire_sft29a_in[2:2]),
	.out(wire_sft29a_out[2:2]));
	soft   sft29a_3
	( 
	.in(wire_sft29a_in[3:3]),
	.out(wire_sft29a_out[3:3]));
	soft   sft29a_4
	( 
	.in(wire_sft29a_in[4:4]),
	.out(wire_sft29a_out[4:4]));
	soft   sft29a_5
	( 
	.in(wire_sft29a_in[5:5]),
	.out(wire_sft29a_out[5:5]));
	soft   sft29a_6
	( 
	.in(wire_sft29a_in[6:6]),
	.out(wire_sft29a_out[6:6]));
	soft   sft29a_7
	( 
	.in(wire_sft29a_in[7:7]),
	.out(wire_sft29a_out[7:7]));
	soft   sft29a_8
	( 
	.in(wire_sft29a_in[8:8]),
	.out(wire_sft29a_out[8:8]));
	soft   sft29a_9
	( 
	.in(wire_sft29a_in[9:9]),
	.out(wire_sft29a_out[9:9]));
	soft   sft29a_10
	( 
	.in(wire_sft29a_in[10:10]),
	.out(wire_sft29a_out[10:10]));
	soft   sft29a_11
	( 
	.in(wire_sft29a_in[11:11]),
	.out(wire_sft29a_out[11:11]));
	soft   sft29a_12
	( 
	.in(wire_sft29a_in[12:12]),
	.out(wire_sft29a_out[12:12]));
	soft   sft29a_13
	( 
	.in(wire_sft29a_in[13:13]),
	.out(wire_sft29a_out[13:13]));
	soft   sft29a_14
	( 
	.in(wire_sft29a_in[14:14]),
	.out(wire_sft29a_out[14:14]));
	soft   sft29a_15
	( 
	.in(wire_sft29a_in[15:15]),
	.out(wire_sft29a_out[15:15]));
	soft   sft29a_16
	( 
	.in(wire_sft29a_in[16:16]),
	.out(wire_sft29a_out[16:16]));
	soft   sft29a_17
	( 
	.in(wire_sft29a_in[17:17]),
	.out(wire_sft29a_out[17:17]));
	soft   sft29a_18
	( 
	.in(wire_sft29a_in[18:18]),
	.out(wire_sft29a_out[18:18]));
	soft   sft29a_19
	( 
	.in(wire_sft29a_in[19:19]),
	.out(wire_sft29a_out[19:19]));
	soft   sft29a_20
	( 
	.in(wire_sft29a_in[20:20]),
	.out(wire_sft29a_out[20:20]));
	soft   sft29a_21
	( 
	.in(wire_sft29a_in[21:21]),
	.out(wire_sft29a_out[21:21]));
	soft   sft29a_22
	( 
	.in(wire_sft29a_in[22:22]),
	.out(wire_sft29a_out[22:22]));
	soft   sft29a_23
	( 
	.in(wire_sft29a_in[23:23]),
	.out(wire_sft29a_out[23:23]));
	soft   sft29a_24
	( 
	.in(wire_sft29a_in[24:24]),
	.out(wire_sft29a_out[24:24]));
	soft   sft29a_25
	( 
	.in(wire_sft29a_in[25:25]),
	.out(wire_sft29a_out[25:25]));
	soft   sft29a_26
	( 
	.in(wire_sft29a_in[26:26]),
	.out(wire_sft29a_out[26:26]));
	soft   sft29a_27
	( 
	.in(wire_sft29a_in[27:27]),
	.out(wire_sft29a_out[27:27]));
	soft   sft29a_28
	( 
	.in(wire_sft29a_in[28:28]),
	.out(wire_sft29a_out[28:28]));
	soft   sft29a_29
	( 
	.in(wire_sft29a_in[29:29]),
	.out(wire_sft29a_out[29:29]));
	soft   sft29a_30
	( 
	.in(wire_sft29a_in[30:30]),
	.out(wire_sft29a_out[30:30]));
	soft   sft29a_31
	( 
	.in(wire_sft29a_in[31:31]),
	.out(wire_sft29a_out[31:31]));
	soft   sft29a_32
	( 
	.in(wire_sft29a_in[32:32]),
	.out(wire_sft29a_out[32:32]));
	soft   sft29a_33
	( 
	.in(wire_sft29a_in[33:33]),
	.out(wire_sft29a_out[33:33]));
	assign
		wire_sft29a_in = {w1048w, {w1048w, {w1048w, {w1048w, {w1048w, {w1048w, {w1048w, {w1048w, {w1048w, {w1048w, {w1048w, {w1048w, {w1048w, {w1048w, {w1048w, {w1048w, {w1048w, {wire_mac_out26_dataout[16], {wire_mac_out26_dataout[15], {wire_mac_out26_dataout[14], {wire_mac_out26_dataout[13], {wire_mac_out26_dataout[12], {wire_mac_out26_dataout[11], {wire_mac_out26_dataout[10], {wire_mac_out26_dataout[9], {wire_mac_out26_dataout[8], {wire_mac_out26_dataout[7], {wire_mac_out26_dataout[6], {wire_mac_out26_dataout[5], {wire_mac_out26_dataout[4], {wire_mac_out26_dataout[3], {wire_mac_out26_dataout[2], {wire_mac_out26_dataout[1:0]}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}};
	soft   sft30a_0
	( 
	.in(wire_sft30a_in[0:0]),
	.out(wire_sft30a_out[0:0]));
	soft   sft30a_1
	( 
	.in(wire_sft30a_in[1:1]),
	.out(wire_sft30a_out[1:1]));
	soft   sft30a_2
	( 
	.in(wire_sft30a_in[2:2]),
	.out(wire_sft30a_out[2:2]));
	soft   sft30a_3
	( 
	.in(wire_sft30a_in[3:3]),
	.out(wire_sft30a_out[3:3]));
	soft   sft30a_4
	( 
	.in(wire_sft30a_in[4:4]),
	.out(wire_sft30a_out[4:4]));
	soft   sft30a_5
	( 
	.in(wire_sft30a_in[5:5]),
	.out(wire_sft30a_out[5:5]));
	soft   sft30a_6
	( 
	.in(wire_sft30a_in[6:6]),
	.out(wire_sft30a_out[6:6]));
	soft   sft30a_7
	( 
	.in(wire_sft30a_in[7:7]),
	.out(wire_sft30a_out[7:7]));
	soft   sft30a_8
	( 
	.in(wire_sft30a_in[8:8]),
	.out(wire_sft30a_out[8:8]));
	soft   sft30a_9
	( 
	.in(wire_sft30a_in[9:9]),
	.out(wire_sft30a_out[9:9]));
	soft   sft30a_10
	( 
	.in(wire_sft30a_in[10:10]),
	.out(wire_sft30a_out[10:10]));
	soft   sft30a_11
	( 
	.in(wire_sft30a_in[11:11]),
	.out(wire_sft30a_out[11:11]));
	soft   sft30a_12
	( 
	.in(wire_sft30a_in[12:12]),
	.out(wire_sft30a_out[12:12]));
	soft   sft30a_13
	( 
	.in(wire_sft30a_in[13:13]),
	.out(wire_sft30a_out[13:13]));
	soft   sft30a_14
	( 
	.in(wire_sft30a_in[14:14]),
	.out(wire_sft30a_out[14:14]));
	soft   sft30a_15
	( 
	.in(wire_sft30a_in[15:15]),
	.out(wire_sft30a_out[15:15]));
	soft   sft30a_16
	( 
	.in(wire_sft30a_in[16:16]),
	.out(wire_sft30a_out[16:16]));
	soft   sft30a_17
	( 
	.in(wire_sft30a_in[17:17]),
	.out(wire_sft30a_out[17:17]));
	soft   sft30a_18
	( 
	.in(wire_sft30a_in[18:18]),
	.out(wire_sft30a_out[18:18]));
	soft   sft30a_19
	( 
	.in(wire_sft30a_in[19:19]),
	.out(wire_sft30a_out[19:19]));
	soft   sft30a_20
	( 
	.in(wire_sft30a_in[20:20]),
	.out(wire_sft30a_out[20:20]));
	soft   sft30a_21
	( 
	.in(wire_sft30a_in[21:21]),
	.out(wire_sft30a_out[21:21]));
	soft   sft30a_22
	( 
	.in(wire_sft30a_in[22:22]),
	.out(wire_sft30a_out[22:22]));
	soft   sft30a_23
	( 
	.in(wire_sft30a_in[23:23]),
	.out(wire_sft30a_out[23:23]));
	soft   sft30a_24
	( 
	.in(wire_sft30a_in[24:24]),
	.out(wire_sft30a_out[24:24]));
	soft   sft30a_25
	( 
	.in(wire_sft30a_in[25:25]),
	.out(wire_sft30a_out[25:25]));
	soft   sft30a_26
	( 
	.in(wire_sft30a_in[26:26]),
	.out(wire_sft30a_out[26:26]));
	soft   sft30a_27
	( 
	.in(wire_sft30a_in[27:27]),
	.out(wire_sft30a_out[27:27]));
	soft   sft30a_28
	( 
	.in(wire_sft30a_in[28:28]),
	.out(wire_sft30a_out[28:28]));
	soft   sft30a_29
	( 
	.in(wire_sft30a_in[29:29]),
	.out(wire_sft30a_out[29:29]));
	soft   sft30a_30
	( 
	.in(wire_sft30a_in[30:30]),
	.out(wire_sft30a_out[30:30]));
	soft   sft30a_31
	( 
	.in(wire_sft30a_in[31:31]),
	.out(wire_sft30a_out[31:31]));
	soft   sft30a_32
	( 
	.in(wire_sft30a_in[32:32]),
	.out(wire_sft30a_out[32:32]));
	soft   sft30a_33
	( 
	.in(wire_sft30a_in[33:33]),
	.out(wire_sft30a_out[33:33]));
	assign
		wire_sft30a_in = wire_add27_result;
	assign
		result = w1169w[50:0],
		w1048w = 1'b0,
		w1169w = {wire_sft30a_out[33:32], wire_sft30a_out[31:30], wire_sft30a_out[29:28], wire_sft30a_out[27:26], wire_sft30a_out[25:24], wire_sft30a_out[23:22], wire_sft30a_out[21:20], wire_sft30a_out[19:18], wire_sft30a_out[17:16], wire_sft30a_out[15:14], wire_sft30a_out[13:12], wire_sft30a_out[11:10], wire_sft30a_out[9:8], wire_sft30a_out[7:6], wire_sft30a_out[5:4], wire_sft30a_out[3:2], wire_sft30a_out[1:0], wire_mac_out24_dataout[17], wire_mac_out24_dataout[16], wire_mac_out24_dataout[15], wire_mac_out24_dataout[14], wire_mac_out24_dataout[13], wire_mac_out24_dataout[12], wire_mac_out24_dataout[11], wire_mac_out24_dataout[10], wire_mac_out24_dataout[9], wire_mac_out24_dataout[8], wire_mac_out24_dataout[7], wire_mac_out24_dataout[6], wire_mac_out24_dataout[5], wire_mac_out24_dataout[4], wire_mac_out24_dataout[3], wire_mac_out24_dataout[2], wire_mac_out24_dataout[1], wire_mac_out24_dataout[0]};
endmodule //fp_div_mult123

//synthesis_resources = dsp_9bit 16 lut 194 M9K 1 mux21 74 reg 349 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  fp_div_altfp_div_pst
	( 
	aclr,
	clk_en,
	clock,
	dataa,
	datab,
	nan,
	result,
	zero) /* synthesis synthesis_clearbox=1 */;
	input   aclr;
	input   clk_en;
	input   clock;
	input   [31:0]  dataa;
	input   [31:0]  datab;
	output   nan;
	output   [31:0]  result;
	output   zero;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   aclr;
	tri1   clk_en;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [8:0]   wire_altsyncram3_q_a;
	reg	a_is_infinity_dffe_0;
	reg	a_is_infinity_dffe_1;
	reg	a_is_infinity_dffe_2;
	reg	a_is_infinity_dffe_3;
	reg	a_is_infinity_dffe_4;
	reg	a_zero_b_not_dffe_0;
	reg	a_zero_b_not_dffe_1;
	reg	a_zero_b_not_dffe_2;
	reg	a_zero_b_not_dffe_3;
	reg	a_zero_b_not_dffe_4;
	reg	[33:0]	b1_dffe_0;
	reg	b_is_infinity_dffe_0;
	reg	b_is_infinity_dffe_1;
	reg	b_is_infinity_dffe_2;
	reg	b_is_infinity_dffe_3;
	reg	b_is_infinity_dffe_4;
	reg	both_exp_zeros_dffe;
	reg	divbyzero_pipe_dffe_0;
	reg	divbyzero_pipe_dffe_1;
	reg	divbyzero_pipe_dffe_2;
	reg	divbyzero_pipe_dffe_3;
	reg	divbyzero_pipe_dffe_4;
	reg	[16:0]	e1_dffe_0;
	reg	[16:0]	e1_dffe_1;
	reg	[7:0]	exp_result_dffe_0;
	reg	[7:0]	exp_result_dffe_1;
	reg	[7:0]	exp_result_dffe_2;
	reg	[7:0]	exp_result_dffe_3;
	reg	frac_a_smaller_dffe1;
	reg	[22:0]	man_a_dffe1_dffe1;
	reg	[22:0]	man_b_dffe1_dffe1;
	reg	[22:0]	man_result_dffe;
	reg	nan_pipe_dffe_0;
	reg	nan_pipe_dffe_1;
	reg	nan_pipe_dffe_2;
	reg	nan_pipe_dffe_3;
	reg	nan_pipe_dffe_4;
	reg	nan_pipe_dffe_5;
	reg	overflow_dffe_0;
	reg	overflow_dffe_1;
	reg	overflow_dffe_2;
	reg	[16:0]	quotient_j_dffe;
	reg	[16:0]	quotient_k_dffe_0;
	reg	[49:0]	remainder_j_dffe_0;
	reg	[49:0]	remainder_j_dffe_1;
	reg	sign_pipe_dffe_0;
	reg	sign_pipe_dffe_1;
	reg	sign_pipe_dffe_2;
	reg	sign_pipe_dffe_3;
	reg	sign_pipe_dffe_4;
	reg	sign_pipe_dffe_5;
	reg	underflow_dffe_0;
	reg	underflow_dffe_1;
	reg	underflow_dffe_2;
	reg	zero_dffe;
	reg	zero_pipe_dffe_0;
	reg	zero_pipe_dffe_1;
	reg	zero_pipe_dffe_2;
	reg	zero_pipe_dffe_3;
	reg	zero_pipe_dffe_4;
	(* ALTERA_ATTRIBUTE = {"POWER_UP_LEVEL=LOW"} *)
	reg	[8:0]	wire_bias_addition_pipeline_dffe_Q;
	wire	[8:0]	wire_bias_addition_pipeline_dffe_D;
	(* ALTERA_ATTRIBUTE = {"POWER_UP_LEVEL=LOW"} *)
	reg	[0:0]	wire_bias_addition_overflow_dffe_Q;
	wire	[0:0]	wire_bias_addition_overflow_dffe_D;
	wire	[8:0]	wire_bias_addition_result_int;
	wire	wire_bias_addition_aclr;
	wire	wire_bias_addition_clken;
	wire	wire_bias_addition_clock;
	wire	[8:0]	wire_bias_addition_dataa;
	wire	[8:0]	wire_bias_addition_datab;
	wire	wire_bias_addition_overflow;
	wire	[8:0]	wire_bias_addition_result;
	(* ALTERA_ATTRIBUTE = {"POWER_UP_LEVEL=LOW"} *)
	reg	[8:0]	wire_exp_sub_pipeline_dffe_Q;
	wire	[8:0]	wire_exp_sub_pipeline_dffe_D;
	wire	[8:0]	wire_exp_sub_result_int;
	wire	wire_exp_sub_aclr;
	wire	wire_exp_sub_clken;
	wire	wire_exp_sub_clock;
	wire	[8:0]	wire_exp_sub_dataa;
	wire	[8:0]	wire_exp_sub_datab;
	wire	[8:0]	wire_exp_sub_result;
	wire	[31:0]	wire_quotient_process_result_int;
	wire	wire_quotient_process_cin;
	wire	[30:0]	wire_quotient_process_dataa;
	wire	[30:0]	wire_quotient_process_datab;
	wire	[30:0]	wire_quotient_process_result;
	wire	[49:0]	wire_remainder_sub_0_dataa;
	wire	[49:0]	wire_remainder_sub_0_datab;
	wire	[49:0]	wire_remainder_sub_0_result;
	reg	wire_cmpr2_alb_int;
	wire	wire_cmpr2_alb;
	wire	[22:0]	wire_cmpr2_dataa;
	wire	[22:0]	wire_cmpr2_datab;
	wire  [34:0]   wire_a1_prod_result;
	wire  [33:0]   wire_b1_prod_result;
	wire  [33:0]   wire_q_partial_0_result;
	wire  [33:0]   wire_q_partial_1_result;
	wire  [50:0]   wire_remainder_mult_0_result;
	wire	[7:0]wire_exp_result_muxa_dataout;
	wire	[24:0]wire_man_a_adjusteda_dataout;
	wire	[22:0]wire_man_result_muxa_dataout;
	wire	[8:0]wire_select_bias_2a_dataout;
	wire	[8:0]wire_select_biasa_dataout;
	wire  a_is_infinity_w;
	wire  a_is_nan_w;
	wire  a_zero_b_not;
	wire  [33:0]  b1_dffe_w;
	wire  b_is_infinity_w;
	wire  b_is_nan_w;
	wire  bias_addition_overf_w;
	wire  [7:0]  bias_addition_w;
	wire  both_exp_zeros;
	wire  [8:0]  e0_dffe1_wo;
	wire  [8:0]  e0_w;
	wire  [50:0]  e1_w;
	wire  [7:0]  exp_a_all_one_w;
	wire  [7:0]  exp_a_not_zero_w;
	wire  [7:0]  exp_add_output_all_one;
	wire  [7:0]  exp_add_output_not_zero;
	wire  [7:0]  exp_b_all_one_w;
	wire  [7:0]  exp_b_not_zero_w;
	wire  [7:0]  exp_result_mux_out;
	wire  exp_result_mux_sel_w;
	wire  [7:0]  exp_result_w;
	wire  exp_sign_w;
	wire  [8:0]  exp_sub_a_w;
	wire  [8:0]  exp_sub_b_w;
	wire  [8:0]  exp_sub_w;
	wire  frac_a_smaller_dffe1_wi;
	wire  frac_a_smaller_dffe1_wo;
	wire  frac_a_smaller_w;
	wire  guard_bit;
	wire  [24:0]  man_a_adjusted_w;
	wire  [22:0]  man_a_dffe1_wi;
	wire  [22:0]  man_a_dffe1_wo;
	wire  [22:0]  man_a_not_zero_w;
	wire  [23:0]  man_b_adjusted_w;
	wire  [22:0]  man_b_dffe1_wi;
	wire  [22:0]  man_b_dffe1_wo;
	wire  [22:0]  man_b_not_zero_w;
	wire  [22:0]  man_result_dffe_wi;
	wire  [22:0]  man_result_dffe_wo;
	wire  man_result_mux_select;
	wire  [22:0]  man_result_w;
	wire  [22:0]  man_zeros_w;
	wire  [7:0]  overflow_ones_w;
	wire  overflow_w;
	wire  [61:0]  quotient_accumulate_w;
	wire  quotient_process_cin_w;
	wire  [99:0]  remainder_j_w;
	wire  round_bit;
	wire  [8:0]  select_bias_out_2_w;
	wire  [8:0]  select_bias_out_w;
	wire  [4:0]  sticky_bits;
	wire  underflow_w;
	wire  [7:0]  underflow_zeros_w;
	wire  [8:0]  value_add_one_w;
	wire  [8:0]  value_normal_w;
	wire  [8:0]  value_zero_w;
	wire  zero_dffe_wi;
	wire  zero_dffe_wo;

	fp_div_altsyncram   altsyncram3
	( 
	.address_a(datab[22:14]),
	.clock0(clock),
	.clocken0(clk_en),
	.q_a(wire_altsyncram3_q_a));
	// synopsys translate_off
	initial
		a_is_infinity_dffe_0 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) a_is_infinity_dffe_0 <= 1'b0;
		else if  (clk_en == 1'b1)   a_is_infinity_dffe_0 <= a_is_infinity_w;
	// synopsys translate_off
	initial
		a_is_infinity_dffe_1 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) a_is_infinity_dffe_1 <= 1'b0;
		else if  (clk_en == 1'b1)   a_is_infinity_dffe_1 <= a_is_infinity_dffe_0;
	// synopsys translate_off
	initial
		a_is_infinity_dffe_2 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) a_is_infinity_dffe_2 <= 1'b0;
		else if  (clk_en == 1'b1)   a_is_infinity_dffe_2 <= a_is_infinity_dffe_1;
	// synopsys translate_off
	initial
		a_is_infinity_dffe_3 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) a_is_infinity_dffe_3 <= 1'b0;
		else if  (clk_en == 1'b1)   a_is_infinity_dffe_3 <= a_is_infinity_dffe_2;
	// synopsys translate_off
	initial
		a_is_infinity_dffe_4 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) a_is_infinity_dffe_4 <= 1'b0;
		else if  (clk_en == 1'b1)   a_is_infinity_dffe_4 <= a_is_infinity_dffe_3;
	// synopsys translate_off
	initial
		a_zero_b_not_dffe_0 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) a_zero_b_not_dffe_0 <= 1'b0;
		else if  (clk_en == 1'b1)   a_zero_b_not_dffe_0 <= a_zero_b_not;
	// synopsys translate_off
	initial
		a_zero_b_not_dffe_1 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) a_zero_b_not_dffe_1 <= 1'b0;
		else if  (clk_en == 1'b1)   a_zero_b_not_dffe_1 <= a_zero_b_not_dffe_0;
	// synopsys translate_off
	initial
		a_zero_b_not_dffe_2 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) a_zero_b_not_dffe_2 <= 1'b0;
		else if  (clk_en == 1'b1)   a_zero_b_not_dffe_2 <= a_zero_b_not_dffe_1;
	// synopsys translate_off
	initial
		a_zero_b_not_dffe_3 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) a_zero_b_not_dffe_3 <= 1'b0;
		else if  (clk_en == 1'b1)   a_zero_b_not_dffe_3 <= a_zero_b_not_dffe_2;
	// synopsys translate_off
	initial
		a_zero_b_not_dffe_4 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) a_zero_b_not_dffe_4 <= 1'b0;
		else if  (clk_en == 1'b1)   a_zero_b_not_dffe_4 <= a_zero_b_not_dffe_3;
	// synopsys translate_off
	initial
		b1_dffe_0 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) b1_dffe_0 <= 34'b0;
		else if  (clk_en == 1'b1)   b1_dffe_0 <= wire_b1_prod_result;
	// synopsys translate_off
	initial
		b_is_infinity_dffe_0 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) b_is_infinity_dffe_0 <= 1'b0;
		else if  (clk_en == 1'b1)   b_is_infinity_dffe_0 <= b_is_infinity_w;
	// synopsys translate_off
	initial
		b_is_infinity_dffe_1 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) b_is_infinity_dffe_1 <= 1'b0;
		else if  (clk_en == 1'b1)   b_is_infinity_dffe_1 <= b_is_infinity_dffe_0;
	// synopsys translate_off
	initial
		b_is_infinity_dffe_2 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) b_is_infinity_dffe_2 <= 1'b0;
		else if  (clk_en == 1'b1)   b_is_infinity_dffe_2 <= b_is_infinity_dffe_1;
	// synopsys translate_off
	initial
		b_is_infinity_dffe_3 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) b_is_infinity_dffe_3 <= 1'b0;
		else if  (clk_en == 1'b1)   b_is_infinity_dffe_3 <= b_is_infinity_dffe_2;
	// synopsys translate_off
	initial
		b_is_infinity_dffe_4 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) b_is_infinity_dffe_4 <= 1'b0;
		else if  (clk_en == 1'b1)   b_is_infinity_dffe_4 <= b_is_infinity_dffe_3;
	// synopsys translate_off
	initial
		both_exp_zeros_dffe = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) both_exp_zeros_dffe <= 1'b0;
		else if  (clk_en == 1'b1)   both_exp_zeros_dffe <= ((~ exp_b_not_zero_w[7]) & (~ exp_a_not_zero_w[7]));
	// synopsys translate_off
	initial
		divbyzero_pipe_dffe_0 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) divbyzero_pipe_dffe_0 <= 1'b0;
		else if  (clk_en == 1'b1)   divbyzero_pipe_dffe_0 <= ((((~ exp_b_not_zero_w[7]) & (~ a_is_nan_w)) & exp_a_not_zero_w[7]) & (~ a_is_infinity_w));
	// synopsys translate_off
	initial
		divbyzero_pipe_dffe_1 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) divbyzero_pipe_dffe_1 <= 1'b0;
		else if  (clk_en == 1'b1)   divbyzero_pipe_dffe_1 <= divbyzero_pipe_dffe_0;
	// synopsys translate_off
	initial
		divbyzero_pipe_dffe_2 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) divbyzero_pipe_dffe_2 <= 1'b0;
		else if  (clk_en == 1'b1)   divbyzero_pipe_dffe_2 <= divbyzero_pipe_dffe_1;
	// synopsys translate_off
	initial
		divbyzero_pipe_dffe_3 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) divbyzero_pipe_dffe_3 <= 1'b0;
		else if  (clk_en == 1'b1)   divbyzero_pipe_dffe_3 <= divbyzero_pipe_dffe_2;
	// synopsys translate_off
	initial
		divbyzero_pipe_dffe_4 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) divbyzero_pipe_dffe_4 <= 1'b0;
		else if  (clk_en == 1'b1)   divbyzero_pipe_dffe_4 <= divbyzero_pipe_dffe_3;
	// synopsys translate_off
	initial
		e1_dffe_0 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) e1_dffe_0 <= 17'b0;
		else if  (clk_en == 1'b1)   e1_dffe_0 <= e1_w[16:0];
	// synopsys translate_off
	initial
		e1_dffe_1 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) e1_dffe_1 <= 17'b0;
		else if  (clk_en == 1'b1)   e1_dffe_1 <= e1_w[33:17];
	// synopsys translate_off
	initial
		exp_result_dffe_0 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) exp_result_dffe_0 <= 8'b0;
		else if  (clk_en == 1'b1)   exp_result_dffe_0 <= exp_result_mux_out;
	// synopsys translate_off
	initial
		exp_result_dffe_1 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) exp_result_dffe_1 <= 8'b0;
		else if  (clk_en == 1'b1)   exp_result_dffe_1 <= exp_result_dffe_0;
	// synopsys translate_off
	initial
		exp_result_dffe_2 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) exp_result_dffe_2 <= 8'b0;
		else if  (clk_en == 1'b1)   exp_result_dffe_2 <= exp_result_dffe_1;
	// synopsys translate_off
	initial
		exp_result_dffe_3 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) exp_result_dffe_3 <= 8'b0;
		else if  (clk_en == 1'b1)   exp_result_dffe_3 <= exp_result_dffe_2;
	// synopsys translate_off
	initial
		frac_a_smaller_dffe1 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) frac_a_smaller_dffe1 <= 1'b0;
		else if  (clk_en == 1'b1)   frac_a_smaller_dffe1 <= frac_a_smaller_dffe1_wi;
	// synopsys translate_off
	initial
		man_a_dffe1_dffe1 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) man_a_dffe1_dffe1 <= 23'b0;
		else if  (clk_en == 1'b1)   man_a_dffe1_dffe1 <= man_a_dffe1_wi;
	// synopsys translate_off
	initial
		man_b_dffe1_dffe1 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) man_b_dffe1_dffe1 <= 23'b0;
		else if  (clk_en == 1'b1)   man_b_dffe1_dffe1 <= man_b_dffe1_wi;
	// synopsys translate_off
	initial
		man_result_dffe = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) man_result_dffe <= 23'b0;
		else if  (clk_en == 1'b1)   man_result_dffe <= man_result_dffe_wi;
	// synopsys translate_off
	initial
		nan_pipe_dffe_0 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) nan_pipe_dffe_0 <= 1'b0;
		else if  (clk_en == 1'b1)   nan_pipe_dffe_0 <= (((a_is_nan_w | b_is_nan_w) | (a_is_infinity_w & b_is_infinity_w)) | ((~ exp_a_not_zero_w[7]) & (~ exp_b_not_zero_w[7])));
	// synopsys translate_off
	initial
		nan_pipe_dffe_1 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) nan_pipe_dffe_1 <= 1'b0;
		else if  (clk_en == 1'b1)   nan_pipe_dffe_1 <= nan_pipe_dffe_0;
	// synopsys translate_off
	initial
		nan_pipe_dffe_2 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) nan_pipe_dffe_2 <= 1'b0;
		else if  (clk_en == 1'b1)   nan_pipe_dffe_2 <= nan_pipe_dffe_1;
	// synopsys translate_off
	initial
		nan_pipe_dffe_3 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) nan_pipe_dffe_3 <= 1'b0;
		else if  (clk_en == 1'b1)   nan_pipe_dffe_3 <= nan_pipe_dffe_2;
	// synopsys translate_off
	initial
		nan_pipe_dffe_4 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) nan_pipe_dffe_4 <= 1'b0;
		else if  (clk_en == 1'b1)   nan_pipe_dffe_4 <= nan_pipe_dffe_3;
	// synopsys translate_off
	initial
		nan_pipe_dffe_5 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) nan_pipe_dffe_5 <= 1'b0;
		else if  (clk_en == 1'b1)   nan_pipe_dffe_5 <= nan_pipe_dffe_4;
	// synopsys translate_off
	initial
		overflow_dffe_0 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) overflow_dffe_0 <= 1'b0;
		else if  (clk_en == 1'b1)   overflow_dffe_0 <= overflow_w;
	// synopsys translate_off
	initial
		overflow_dffe_1 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) overflow_dffe_1 <= 1'b0;
		else if  (clk_en == 1'b1)   overflow_dffe_1 <= overflow_dffe_0;
	// synopsys translate_off
	initial
		overflow_dffe_2 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) overflow_dffe_2 <= 1'b0;
		else if  (clk_en == 1'b1)   overflow_dffe_2 <= overflow_dffe_1;
	// synopsys translate_off
	initial
		quotient_j_dffe = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) quotient_j_dffe <= 17'b0;
		else if  (clk_en == 1'b1)   quotient_j_dffe <= wire_q_partial_0_result[32:16];
	// synopsys translate_off
	initial
		quotient_k_dffe_0 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) quotient_k_dffe_0 <= 17'b0;
		else if  (clk_en == 1'b1)   quotient_k_dffe_0 <= quotient_accumulate_w[30:14];
	// synopsys translate_off
	initial
		remainder_j_dffe_0 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) remainder_j_dffe_0 <= 50'b0;
		else if  (clk_en == 1'b1)   remainder_j_dffe_0 <= remainder_j_w[49:0];
	// synopsys translate_off
	initial
		remainder_j_dffe_1 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) remainder_j_dffe_1 <= 50'b0;
		else if  (clk_en == 1'b1)   remainder_j_dffe_1 <= remainder_j_dffe_0;
	// synopsys translate_off
	initial
		sign_pipe_dffe_0 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) sign_pipe_dffe_0 <= 1'b0;
		else if  (clk_en == 1'b1)   sign_pipe_dffe_0 <= (dataa[31] ^ datab[31]);
	// synopsys translate_off
	initial
		sign_pipe_dffe_1 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) sign_pipe_dffe_1 <= 1'b0;
		else if  (clk_en == 1'b1)   sign_pipe_dffe_1 <= sign_pipe_dffe_0;
	// synopsys translate_off
	initial
		sign_pipe_dffe_2 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) sign_pipe_dffe_2 <= 1'b0;
		else if  (clk_en == 1'b1)   sign_pipe_dffe_2 <= sign_pipe_dffe_1;
	// synopsys translate_off
	initial
		sign_pipe_dffe_3 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) sign_pipe_dffe_3 <= 1'b0;
		else if  (clk_en == 1'b1)   sign_pipe_dffe_3 <= sign_pipe_dffe_2;
	// synopsys translate_off
	initial
		sign_pipe_dffe_4 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) sign_pipe_dffe_4 <= 1'b0;
		else if  (clk_en == 1'b1)   sign_pipe_dffe_4 <= sign_pipe_dffe_3;
	// synopsys translate_off
	initial
		sign_pipe_dffe_5 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) sign_pipe_dffe_5 <= 1'b0;
		else if  (clk_en == 1'b1)   sign_pipe_dffe_5 <= sign_pipe_dffe_4;
	// synopsys translate_off
	initial
		underflow_dffe_0 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) underflow_dffe_0 <= 1'b0;
		else if  (clk_en == 1'b1)   underflow_dffe_0 <= underflow_w;
	// synopsys translate_off
	initial
		underflow_dffe_1 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) underflow_dffe_1 <= 1'b0;
		else if  (clk_en == 1'b1)   underflow_dffe_1 <= underflow_dffe_0;
	// synopsys translate_off
	initial
		underflow_dffe_2 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) underflow_dffe_2 <= 1'b0;
		else if  (clk_en == 1'b1)   underflow_dffe_2 <= underflow_dffe_1;
	// synopsys translate_off
	initial
		zero_dffe = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) zero_dffe <= 1'b0;
		else if  (clk_en == 1'b1)   zero_dffe <= zero_dffe_wi;
	// synopsys translate_off
	initial
		zero_pipe_dffe_0 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) zero_pipe_dffe_0 <= 1'b0;
		else if  (clk_en == 1'b1)   zero_pipe_dffe_0 <= (~ exp_a_not_zero_w[7]);
	// synopsys translate_off
	initial
		zero_pipe_dffe_1 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) zero_pipe_dffe_1 <= 1'b0;
		else if  (clk_en == 1'b1)   zero_pipe_dffe_1 <= zero_pipe_dffe_0;
	// synopsys translate_off
	initial
		zero_pipe_dffe_2 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) zero_pipe_dffe_2 <= 1'b0;
		else if  (clk_en == 1'b1)   zero_pipe_dffe_2 <= zero_pipe_dffe_1;
	// synopsys translate_off
	initial
		zero_pipe_dffe_3 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) zero_pipe_dffe_3 <= 1'b0;
		else if  (clk_en == 1'b1)   zero_pipe_dffe_3 <= zero_pipe_dffe_2;
	// synopsys translate_off
	initial
		zero_pipe_dffe_4 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) zero_pipe_dffe_4 <= 1'b0;
		else if  (clk_en == 1'b1)   zero_pipe_dffe_4 <= zero_pipe_dffe_3;
	assign
		wire_bias_addition_result_int = wire_bias_addition_dataa + wire_bias_addition_datab;
	//synopsys translate_off
	initial
		wire_bias_addition_pipeline_dffe_Q = 0;
	//synopsys translate_on
	always @(posedge wire_bias_addition_clock or posedge wire_bias_addition_aclr)
		if (wire_bias_addition_aclr == 1'b1) wire_bias_addition_pipeline_dffe_Q <= 9'b0;
		else if (wire_bias_addition_clken == 1'b1) wire_bias_addition_pipeline_dffe_Q <= wire_bias_addition_pipeline_dffe_D;
	//synopsys translate_off
	initial
		wire_bias_addition_overflow_dffe_Q = 0;
	//synopsys translate_on
	always @(posedge wire_bias_addition_clock or posedge wire_bias_addition_aclr)
		if (wire_bias_addition_aclr == 1'b1) wire_bias_addition_overflow_dffe_Q <= 1'b0;
		else if (wire_bias_addition_clken == 1'b1) wire_bias_addition_overflow_dffe_Q <= wire_bias_addition_overflow_dffe_D;
	assign
		wire_bias_addition_result = wire_bias_addition_pipeline_dffe_Q[8:0],
		wire_bias_addition_pipeline_dffe_D[8:0] = wire_bias_addition_result_int;
	assign
		wire_bias_addition_overflow = wire_bias_addition_overflow_dffe_Q[0:0],
		wire_bias_addition_overflow_dffe_D[0:0] = ~(wire_bias_addition_dataa[8:8] ^ wire_bias_addition_datab[8:8]) & (wire_bias_addition_dataa[8:8] ^ wire_bias_addition_result_int[8:8]);
	assign
		wire_bias_addition_aclr = aclr,
		wire_bias_addition_clken = clk_en,
		wire_bias_addition_clock = clock,
		wire_bias_addition_dataa = exp_sub_w,
		wire_bias_addition_datab = select_bias_out_2_w;
	assign
		wire_exp_sub_result_int = wire_exp_sub_dataa - wire_exp_sub_datab;
	//synopsys translate_off
	initial
		wire_exp_sub_pipeline_dffe_Q = 0;
	//synopsys translate_on
	always @(posedge wire_exp_sub_clock or posedge wire_exp_sub_aclr)
		if (wire_exp_sub_aclr == 1'b1) wire_exp_sub_pipeline_dffe_Q <= 9'b0;
		else if (wire_exp_sub_clken == 1'b1) wire_exp_sub_pipeline_dffe_Q <= wire_exp_sub_pipeline_dffe_D;
	assign
		wire_exp_sub_result = wire_exp_sub_pipeline_dffe_Q[8:0],
		wire_exp_sub_pipeline_dffe_D[8:0] = wire_exp_sub_result_int;
	assign
		wire_exp_sub_aclr = aclr,
		wire_exp_sub_clken = clk_en,
		wire_exp_sub_clock = clock,
		wire_exp_sub_dataa = exp_sub_a_w,
		wire_exp_sub_datab = exp_sub_b_w;
	assign
		wire_quotient_process_result_int = {wire_quotient_process_dataa, wire_quotient_process_cin} + {wire_quotient_process_datab, wire_quotient_process_cin};
	assign
		wire_quotient_process_result = wire_quotient_process_result_int[31:1];
	assign
		wire_quotient_process_cin = quotient_process_cin_w,
		wire_quotient_process_dataa = {quotient_accumulate_w[61:45], {14{1'b0}}},
		wire_quotient_process_datab = {{14{1'b0}}, wire_q_partial_1_result[32:22], {6{1'b1}}};
	assign
		wire_remainder_sub_0_result = wire_remainder_sub_0_dataa - wire_remainder_sub_0_datab;
	assign
		wire_remainder_sub_0_dataa = {remainder_j_dffe_1[49:15], {15{1'b0}}},
		wire_remainder_sub_0_datab = wire_remainder_mult_0_result[49:0];
	always @(wire_cmpr2_dataa or wire_cmpr2_datab)
	begin
		if (wire_cmpr2_dataa < wire_cmpr2_datab) 
			begin
				wire_cmpr2_alb_int = 1'b1;
			end
		else
			begin
				wire_cmpr2_alb_int = 1'b0;
			end
	end
	assign
		wire_cmpr2_alb = wire_cmpr2_alb_int;
	assign
		wire_cmpr2_dataa = dataa[22:0],
		wire_cmpr2_datab = datab[22:0];
	fp_div_mult   a1_prod
	( 
	.aclr(aclr),
	.clken(clk_en),
	.clock(clock),
	.dataa(man_a_adjusted_w),
	.datab({1'b1, e0_dffe1_wo}),
	.result(wire_a1_prod_result));
	fp_div_mult1   b1_prod
	( 
	.aclr(aclr),
	.clken(clk_en),
	.clock(clock),
	.dataa(man_b_adjusted_w),
	.datab({1'b1, e0_dffe1_wo}),
	.result(wire_b1_prod_result));
	fp_div_mult12   q_partial_0
	( 
	.aclr(aclr),
	.clken(clk_en),
	.clock(clock),
	.dataa(remainder_j_w[49:33]),
	.datab(e1_w[16:0]),
	.result(wire_q_partial_0_result));
	fp_div_mult12   q_partial_1
	( 
	.aclr(aclr),
	.clken(clk_en),
	.clock(clock),
	.dataa(remainder_j_w[99:83]),
	.datab(e1_w[50:34]),
	.result(wire_q_partial_1_result));
	fp_div_mult123   remainder_mult_0
	( 
	.aclr(aclr),
	.clken(clk_en),
	.clock(clock),
	.dataa(b1_dffe_w[33:0]),
	.datab(wire_q_partial_0_result[32:16]),
	.result(wire_remainder_mult_0_result));
	assign		wire_exp_result_muxa_dataout = (exp_result_mux_sel_w === 1'b1) ? underflow_zeros_w : exp_result_w;
	assign		wire_man_a_adjusteda_dataout = (frac_a_smaller_dffe1_wo === 1'b1) ? {1'b1, man_a_dffe1_wo, 1'b0} : {1'b0, 1'b1, man_a_dffe1_wo};
	assign		wire_man_result_muxa_dataout = (man_result_mux_select === 1'b1) ? {nan_pipe_dffe_4, man_zeros_w[21:0]} : wire_quotient_process_result[28:6];
	assign		wire_select_bias_2a_dataout = (both_exp_zeros === 1'b1) ? value_zero_w : select_bias_out_w;
	assign		wire_select_biasa_dataout = (frac_a_smaller_dffe1_wo === 1'b1) ? value_normal_w : value_add_one_w;
	assign
		a_is_infinity_w = (exp_a_all_one_w[7] & (~ man_a_not_zero_w[22])),
		a_is_nan_w = (exp_a_all_one_w[7] & man_a_not_zero_w[22]),
		a_zero_b_not = (exp_b_not_zero_w[7] & (~ exp_a_not_zero_w[7])),
		b1_dffe_w = {b1_dffe_0},
		b_is_infinity_w = (exp_b_all_one_w[7] & (~ man_b_not_zero_w[22])),
		b_is_nan_w = (exp_b_all_one_w[7] & man_b_not_zero_w[22]),
		bias_addition_overf_w = wire_bias_addition_overflow,
		bias_addition_w = wire_bias_addition_result[7:0],
		both_exp_zeros = both_exp_zeros_dffe,
		e0_dffe1_wo = e0_w,
		e0_w = wire_altsyncram3_q_a,
		e1_w = {e1_dffe_1, e1_dffe_0, (~ wire_b1_prod_result[33:17])},
		exp_a_all_one_w = {(dataa[30] & exp_a_all_one_w[6]), (dataa[29] & exp_a_all_one_w[5]), (dataa[28] & exp_a_all_one_w[4]), (dataa[27] & exp_a_all_one_w[3]), (dataa[26] & exp_a_all_one_w[2]), (dataa[25] & exp_a_all_one_w[1]), (dataa[24] & exp_a_all_one_w[0]), dataa[23]},
		exp_a_not_zero_w = {(dataa[30] | exp_a_not_zero_w[6]), (dataa[29] | exp_a_not_zero_w[5]), (dataa[28] | exp_a_not_zero_w[4]), (dataa[27] | exp_a_not_zero_w[3]), (dataa[26] | exp_a_not_zero_w[2]), (dataa[25] | exp_a_not_zero_w[1]), (dataa[24] | exp_a_not_zero_w[0]), dataa[23]},
		exp_add_output_all_one = {(bias_addition_w[7] & exp_add_output_all_one[6]), (bias_addition_w[6] & exp_add_output_all_one[5]), (bias_addition_w[5] & exp_add_output_all_one[4]), (bias_addition_w[4] & exp_add_output_all_one[3]), (bias_addition_w[3] & exp_add_output_all_one[2]), (bias_addition_w[2] & exp_add_output_all_one[1]), (bias_addition_w[1] & exp_add_output_all_one[0]), bias_addition_w[0]},
		exp_add_output_not_zero = {(bias_addition_w[7] | exp_add_output_not_zero[6]), (bias_addition_w[6] | exp_add_output_not_zero[5]), (bias_addition_w[5] | exp_add_output_not_zero[4]), (bias_addition_w[4] | exp_add_output_not_zero[3]), (bias_addition_w[3] | exp_add_output_not_zero[2]), (bias_addition_w[2] | exp_add_output_not_zero[1]), (bias_addition_w[1] | exp_add_output_not_zero[0]), bias_addition_w[0]},
		exp_b_all_one_w = {(datab[30] & exp_b_all_one_w[6]), (datab[29] & exp_b_all_one_w[5]), (datab[28] & exp_b_all_one_w[4]), (datab[27] & exp_b_all_one_w[3]), (datab[26] & exp_b_all_one_w[2]), (datab[25] & exp_b_all_one_w[1]), (datab[24] & exp_b_all_one_w[0]), datab[23]},
		exp_b_not_zero_w = {(datab[30] | exp_b_not_zero_w[6]), (datab[29] | exp_b_not_zero_w[5]), (datab[28] | exp_b_not_zero_w[4]), (datab[27] | exp_b_not_zero_w[3]), (datab[26] | exp_b_not_zero_w[2]), (datab[25] | exp_b_not_zero_w[1]), (datab[24] | exp_b_not_zero_w[0]), datab[23]},
		exp_result_mux_out = wire_exp_result_muxa_dataout,
		exp_result_mux_sel_w = ((((a_zero_b_not_dffe_1 | b_is_infinity_dffe_1) | ((~ bias_addition_overf_w) & exp_sign_w)) | (((~ exp_add_output_not_zero[7]) & (~ bias_addition_overf_w)) & (~ exp_sign_w))) & (~ nan_pipe_dffe_1)),
		exp_result_w = (({8{((~ bias_addition_overf_w) & (~ exp_sign_w))}} & bias_addition_w) | ({8{(((bias_addition_overf_w | divbyzero_pipe_dffe_1) | nan_pipe_dffe_1) | a_is_infinity_dffe_1)}} & overflow_ones_w)),
		exp_sign_w = wire_bias_addition_result[8],
		exp_sub_a_w = {1'b0, dataa[30:23]},
		exp_sub_b_w = {1'b0, datab[30:23]},
		exp_sub_w = wire_exp_sub_result,
		frac_a_smaller_dffe1_wi = frac_a_smaller_w,
		frac_a_smaller_dffe1_wo = frac_a_smaller_dffe1,
		frac_a_smaller_w = wire_cmpr2_alb,
		guard_bit = wire_q_partial_1_result[22],
		man_a_adjusted_w = wire_man_a_adjusteda_dataout,
		man_a_dffe1_wi = dataa[22:0],
		man_a_dffe1_wo = man_a_dffe1_dffe1,
		man_a_not_zero_w = {(dataa[22] | man_a_not_zero_w[21]), (dataa[21] | man_a_not_zero_w[20]), (dataa[20] | man_a_not_zero_w[19]), (dataa[19] | man_a_not_zero_w[18]), (dataa[18] | man_a_not_zero_w[17]), (dataa[17] | man_a_not_zero_w[16]), (dataa[16] | man_a_not_zero_w[15]), (dataa[15] | man_a_not_zero_w[14]), (dataa[14] | man_a_not_zero_w[13]), (dataa[13] | man_a_not_zero_w[12]), (dataa[12] | man_a_not_zero_w[11]), (dataa[11] | man_a_not_zero_w[10]), (dataa[10] | man_a_not_zero_w[9]), (dataa[9] | man_a_not_zero_w[8]), (dataa[8] | man_a_not_zero_w[7]), (dataa[7] | man_a_not_zero_w[6]), (dataa[6] | man_a_not_zero_w[5]), (dataa[5] | man_a_not_zero_w[4]), (dataa[4] | man_a_not_zero_w[3]), (dataa[3] | man_a_not_zero_w[2]), (dataa[2] | man_a_not_zero_w[1]), (dataa[1] | man_a_not_zero_w[0]), dataa[0]},
		man_b_adjusted_w = {1'b1, man_b_dffe1_wo},
		man_b_dffe1_wi = datab[22:0],
		man_b_dffe1_wo = man_b_dffe1_dffe1,
		man_b_not_zero_w = {(datab[22] | man_b_not_zero_w[21]), (datab[21] | man_b_not_zero_w[20]), (datab[20] | man_b_not_zero_w[19]), (datab[19] | man_b_not_zero_w[18]), (datab[18] | man_b_not_zero_w[17]), (datab[17] | man_b_not_zero_w[16]), (datab[16] | man_b_not_zero_w[15]), (datab[15] | man_b_not_zero_w[14]), (datab[14] | man_b_not_zero_w[13]), (datab[13] | man_b_not_zero_w[12]), (datab[12] | man_b_not_zero_w[11]), (datab[11] | man_b_not_zero_w[10]), (datab[10] | man_b_not_zero_w[9]), (datab[9] | man_b_not_zero_w[8]), (datab[8] | man_b_not_zero_w[7]), (datab[7] | man_b_not_zero_w[6]), (datab[6] | man_b_not_zero_w[5]), (datab[5] | man_b_not_zero_w[4]), (datab[4] | man_b_not_zero_w[3]), (datab[3] | man_b_not_zero_w[2]), (datab[2] | man_b_not_zero_w[1]), (datab[1] | man_b_not_zero_w[0]), datab[0]},
		man_result_dffe_wi = man_result_w,
		man_result_dffe_wo = man_result_dffe,
		man_result_mux_select = ((((((overflow_dffe_2 | underflow_dffe_2) | a_zero_b_not_dffe_4) | nan_pipe_dffe_4) | b_is_infinity_dffe_4) | a_is_infinity_dffe_4) | divbyzero_pipe_dffe_4),
		man_result_w = wire_man_result_muxa_dataout,
		man_zeros_w = {23{1'b0}},
		nan = nan_pipe_dffe_5,
		overflow_ones_w = {8{1'b1}},
		overflow_w = ((bias_addition_overf_w | ((exp_add_output_all_one[7] & (~ bias_addition_overf_w)) & (~ exp_sign_w))) & (((~ nan_pipe_dffe_1) & (~ a_is_infinity_dffe_1)) & (~ divbyzero_pipe_dffe_1))),
		quotient_accumulate_w = {quotient_k_dffe_0, {14{1'b0}}, quotient_j_dffe, {14{1'b0}}},
		quotient_process_cin_w = (round_bit & (guard_bit | sticky_bits[4])),
		remainder_j_w = {wire_remainder_sub_0_result[35:0], {14{1'b0}}, wire_a1_prod_result[34:0], {15{1'b0}}},
		result = {sign_pipe_dffe_5, exp_result_dffe_3, man_result_dffe_wo},
		round_bit = wire_q_partial_1_result[21],
		select_bias_out_2_w = wire_select_bias_2a_dataout,
		select_bias_out_w = wire_select_biasa_dataout,
		sticky_bits = {(wire_q_partial_1_result[20] | sticky_bits[3]), (wire_q_partial_1_result[19] | sticky_bits[2]), (wire_q_partial_1_result[18] | sticky_bits[1]), (wire_q_partial_1_result[17] | sticky_bits[0]), wire_q_partial_1_result[16]},
		underflow_w = ((((((~ bias_addition_overf_w) & exp_sign_w) | (((~ exp_add_output_not_zero[7]) & (~ bias_addition_overf_w)) & (~ exp_sign_w))) & (~ nan_pipe_dffe_1)) & (~ a_zero_b_not_dffe_1)) & (~ b_is_infinity_dffe_1)),
		underflow_zeros_w = {8{1'b0}},
		value_add_one_w = 9'b001111111,
		value_normal_w = 9'b001111110,
		value_zero_w = {9{1'b0}},
		zero = zero_dffe_wo,
		zero_dffe_wi = (((zero_pipe_dffe_4 | underflow_dffe_2) | (b_is_infinity_dffe_4 & (~ a_is_infinity_dffe_4))) & (~ nan_pipe_dffe_4)),
		zero_dffe_wo = zero_dffe;
endmodule //fp_div_altfp_div_pst

//synthesis_resources = dsp_9bit 16 lut 194 M9K 1 mux21 74 reg 349 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  fp_div_altfp_div
	( 
	aclr,
	clk_en,
	clock,
	dataa,
	datab,
	nan,
	result,
	zero) /* synthesis synthesis_clearbox=1 */;
	input   aclr;
	input   clk_en;
	input   clock;
	input   [31:0]  dataa;
	input   [31:0]  datab;
	output   nan;
	output   [31:0]  result;
	output   zero;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   aclr;
	tri1   clk_en;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  wire_altfp_div_pst1_nan;
	wire  [31:0]   wire_altfp_div_pst1_result;
	wire  wire_altfp_div_pst1_zero;

	fp_div_altfp_div_pst   altfp_div_pst1
	( 
	.aclr(aclr),
	.clk_en(clk_en),
	.clock(clock),
	.dataa(dataa),
	.datab(datab),
	.nan(wire_altfp_div_pst1_nan),
	.result(wire_altfp_div_pst1_result),
	.zero(wire_altfp_div_pst1_zero));
	assign
		nan = wire_altfp_div_pst1_nan,
		result = wire_altfp_div_pst1_result,
		zero = wire_altfp_div_pst1_zero;
endmodule //fp_div_altfp_div
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module fp_div (
	aclr,
	clk_en,
	clock,
	dataa,
	datab,
	nan,
	result,
	zero)/* synthesis synthesis_clearbox = 1 */;

	input	  aclr;
	input	  clk_en;
	input	  clock;
	input	[31:0]  dataa;
	input	[31:0]  datab;
	output	  nan;
	output	[31:0]  result;
	output	  zero;

	wire  sub_wire0;
	wire  sub_wire1;
	wire [31:0] sub_wire2;
	wire  zero = sub_wire0;
	wire  nan = sub_wire1;
	wire [31:0] result = sub_wire2[31:0];

	fp_div_altfp_div	fp_div_altfp_div_component (
				.aclr (aclr),
				.clk_en (clk_en),
				.clock (clock),
				.datab (datab),
				.dataa (dataa),
				.zero (sub_wire0),
				.nan (sub_wire1),
				.result (sub_wire2));

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Cyclone III"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "1"
// Retrieval info: LIBRARY: altera_mf altera_mf.altera_mf_components.all
// Retrieval info: CONSTANT: DENORMAL_SUPPORT STRING "NO"
// Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "Cyclone III"
// Retrieval info: CONSTANT: OPTIMIZE STRING "SPEED"
// Retrieval info: CONSTANT: PIPELINE NUMERIC "6"
// Retrieval info: CONSTANT: REDUCED_FUNCTIONALITY STRING "NO"
// Retrieval info: CONSTANT: WIDTH_EXP NUMERIC "8"
// Retrieval info: CONSTANT: WIDTH_MAN NUMERIC "23"
// Retrieval info: USED_PORT: aclr 0 0 0 0 INPUT NODEFVAL "aclr"
// Retrieval info: USED_PORT: clk_en 0 0 0 0 INPUT NODEFVAL "clk_en"
// Retrieval info: USED_PORT: clock 0 0 0 0 INPUT NODEFVAL "clock"
// Retrieval info: USED_PORT: dataa 0 0 32 0 INPUT NODEFVAL "dataa[31..0]"
// Retrieval info: USED_PORT: datab 0 0 32 0 INPUT NODEFVAL "datab[31..0]"
// Retrieval info: USED_PORT: nan 0 0 0 0 OUTPUT NODEFVAL "nan"
// Retrieval info: USED_PORT: result 0 0 32 0 OUTPUT NODEFVAL "result[31..0]"
// Retrieval info: USED_PORT: zero 0 0 0 0 OUTPUT NODEFVAL "zero"
// Retrieval info: CONNECT: @aclr 0 0 0 0 aclr 0 0 0 0
// Retrieval info: CONNECT: @clk_en 0 0 0 0 clk_en 0 0 0 0
// Retrieval info: CONNECT: @clock 0 0 0 0 clock 0 0 0 0
// Retrieval info: CONNECT: @dataa 0 0 32 0 dataa 0 0 32 0
// Retrieval info: CONNECT: @datab 0 0 32 0 datab 0 0 32 0
// Retrieval info: CONNECT: nan 0 0 0 0 @nan 0 0 0 0
// Retrieval info: CONNECT: result 0 0 32 0 @result 0 0 32 0
// Retrieval info: CONNECT: zero 0 0 0 0 @zero 0 0 0 0
// Retrieval info: GEN_FILE: TYPE_NORMAL fp_div.vhd TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL fp_div.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL fp_div.cmp TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL fp_div.bsf TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL fp_div_inst.vhd TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL fp_div_syn.v TRUE
